// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<String> createNote({
  required String title,
  required String content,
  List<String>? categories,
  String? workspaceIdentifier,
  String? metaWorkspaceId,
}) => RustLib.instance.api.crateApiNotesCreateNote(
  title: title,
  content: content,
  categories: categories,
  workspaceIdentifier: workspaceIdentifier,
  metaWorkspaceId: metaWorkspaceId,
);

Future<String?> getNote({
  required String identifier,
  String? metaWorkspaceId,
}) => RustLib.instance.api.crateApiNotesGetNote(
  identifier: identifier,
  metaWorkspaceId: metaWorkspaceId,
);

Future<String> getAllNotes({String? metaWorkspaceId}) => RustLib.instance.api
    .crateApiNotesGetAllNotes(metaWorkspaceId: metaWorkspaceId);

Future<String> getRecentlyAddedNotes({String? metaWorkspaceId}) => RustLib
    .instance
    .api
    .crateApiNotesGetRecentlyAddedNotes(metaWorkspaceId: metaWorkspaceId);

Future<String> updateNote({
  required String identifier,
  String? title,
  String? content,
  List<String>? categories,
  String? metaWorkspaceId,
}) => RustLib.instance.api.crateApiNotesUpdateNote(
  identifier: identifier,
  title: title,
  content: content,
  categories: categories,
  metaWorkspaceId: metaWorkspaceId,
);

Future<void> deleteNote({
  required String identifier,
  String? metaWorkspaceId,
}) => RustLib.instance.api.crateApiNotesDeleteNote(
  identifier: identifier,
  metaWorkspaceId: metaWorkspaceId,
);

Future<void> duplicateNote({
  required String recordIdentifier,
  required String previousWorkspaceIdentifier,
  required String targetWorkspaceIdentifier,
}) => RustLib.instance.api.crateApiNotesDuplicateNote(
  recordIdentifier: recordIdentifier,
  previousWorkspaceIdentifier: previousWorkspaceIdentifier,
  targetWorkspaceIdentifier: targetWorkspaceIdentifier,
);

Future<void> transferNote({
  required String recordIdentifier,
  required String previousWorkspaceIdentifier,
  required String targetWorkspaceIdentifier,
}) => RustLib.instance.api.crateApiNotesTransferNote(
  recordIdentifier: recordIdentifier,
  previousWorkspaceIdentifier: previousWorkspaceIdentifier,
  targetWorkspaceIdentifier: targetWorkspaceIdentifier,
);
