// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `parse_priority`

Future<String> createTodo({
  required String title,
  String? description,
  required String priority,
  String? dueDate,
  String? workspaceIdentifier,
  String? metaWorkspaceId,
}) => RustLib.instance.api.crateApiTodoCreateTodo(
  title: title,
  description: description,
  priority: priority,
  dueDate: dueDate,
  workspaceIdentifier: workspaceIdentifier,
  metaWorkspaceId: metaWorkspaceId,
);

Future<String?> getTodo({
  required String identifier,
  String? metaWorkspaceId,
}) => RustLib.instance.api.crateApiTodoGetTodo(
  identifier: identifier,
  metaWorkspaceId: metaWorkspaceId,
);

Future<String> getAllTodos({String? metaWorkspaceId}) => RustLib.instance.api
    .crateApiTodoGetAllTodos(metaWorkspaceId: metaWorkspaceId);

Future<String> updateTodo({
  required String identifier,
  String? title,
  String? description,
  String? priority,
  String? dueDate,
  String? metaWorkspaceId,
}) => RustLib.instance.api.crateApiTodoUpdateTodo(
  identifier: identifier,
  title: title,
  description: description,
  priority: priority,
  dueDate: dueDate,
  metaWorkspaceId: metaWorkspaceId,
);

Future<void> deleteTodo({
  required String identifier,
  String? metaWorkspaceId,
}) => RustLib.instance.api.crateApiTodoDeleteTodo(
  identifier: identifier,
  metaWorkspaceId: metaWorkspaceId,
);

Future<String> markTodoDone({
  required String identifier,
  required bool done,
  String? metaWorkspaceId,
}) => RustLib.instance.api.crateApiTodoMarkTodoDone(
  identifier: identifier,
  done: done,
  metaWorkspaceId: metaWorkspaceId,
);

Future<String> changeTodoPriority({
  required String identifier,
  required String priority,
  String? metaWorkspaceId,
}) => RustLib.instance.api.crateApiTodoChangeTodoPriority(
  identifier: identifier,
  priority: priority,
  metaWorkspaceId: metaWorkspaceId,
);

/// `due_date` — ISO 8601 date string (`"YYYY-MM-DD"`), or `None` to clear.
Future<String> updateTodoDueDate({
  required String identifier,
  String? dueDate,
  String? metaWorkspaceId,
}) => RustLib.instance.api.crateApiTodoUpdateTodoDueDate(
  identifier: identifier,
  dueDate: dueDate,
  metaWorkspaceId: metaWorkspaceId,
);

Future<void> duplicateTodo({
  required String recordIdentifier,
  required String previousWorkspaceIdentifier,
  required String targetWorkspaceIdentifier,
}) => RustLib.instance.api.crateApiTodoDuplicateTodo(
  recordIdentifier: recordIdentifier,
  previousWorkspaceIdentifier: previousWorkspaceIdentifier,
  targetWorkspaceIdentifier: targetWorkspaceIdentifier,
);

Future<void> transferTodo({
  required String recordIdentifier,
  required String previousWorkspaceIdentifier,
  required String targetWorkspaceIdentifier,
}) => RustLib.instance.api.crateApiTodoTransferTodo(
  recordIdentifier: recordIdentifier,
  previousWorkspaceIdentifier: previousWorkspaceIdentifier,
  targetWorkspaceIdentifier: targetWorkspaceIdentifier,
);
