// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/bookmarks.dart';
import 'api/notes.dart';
import 'api/recycle_bin.dart';
import 'api/reminders.dart';
import 'api/simple.dart';
import 'api/snippets.dart';
import 'api/todo.dart';
import 'api/user_preference.dart';
import 'api/workspaces.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  String cst_encode_String(String raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  bool cst_encode_box_autoadd_bool(bool raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_bool(raw);
  }

  @protected
  JSAny cst_encode_list_String(List<String> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_String).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_prim_u_8_strict(Uint8List raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.jsify()!;
  }

  @protected
  String? cst_encode_opt_String(String? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_String(raw);
  }

  @protected
  bool? cst_encode_opt_box_autoadd_bool(bool? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_bool(raw);
  }

  @protected
  JSAny? cst_encode_opt_list_String(List<String>? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_list_String(raw);
  }

  @protected
  bool cst_encode_bool(bool raw);

  @protected
  int cst_encode_u_8(int raw);

  @protected
  void cst_encode_unit(void raw);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_String(List<String>? self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void wire__crate__api__todo__change_todo_priority(
    NativePortType port_,
    String identifier,
    String priority,
    String? meta_workspace_id,
  ) => wasmModule.wire__crate__api__todo__change_todo_priority(
    port_,
    identifier,
    priority,
    meta_workspace_id,
  );

  void wire__crate__api__bookmarks__create_bookmark(
    NativePortType port_,
    String title,
    String url,
    String tag,
    String? workspace_identifier,
    String? meta_workspace_id,
  ) => wasmModule.wire__crate__api__bookmarks__create_bookmark(
    port_,
    title,
    url,
    tag,
    workspace_identifier,
    meta_workspace_id,
  );

  void wire__crate__api__notes__create_note(
    NativePortType port_,
    String title,
    String content,
    JSAny? categories,
    String? workspace_identifier,
    String? meta_workspace_id,
  ) => wasmModule.wire__crate__api__notes__create_note(
    port_,
    title,
    content,
    categories,
    workspace_identifier,
    meta_workspace_id,
  );

  void wire__crate__api__recycle_bin__create_recycle_bin_entry(
    NativePortType port_,
    String item_id,
    String item_type,
    String payload,
    String? meta_workspace_id,
  ) => wasmModule.wire__crate__api__recycle_bin__create_recycle_bin_entry(
    port_,
    item_id,
    item_type,
    payload,
    meta_workspace_id,
  );

  void wire__crate__api__reminders__create_reminder(
    NativePortType port_,
    String title,
    String? description,
    String remind_at,
    bool recurring,
    String? recurrence_rule,
    String? alarm_sound,
    String? workspace_identifier,
    String? meta_workspace_id,
  ) => wasmModule.wire__crate__api__reminders__create_reminder(
    port_,
    title,
    description,
    remind_at,
    recurring,
    recurrence_rule,
    alarm_sound,
    workspace_identifier,
    meta_workspace_id,
  );

  void wire__crate__api__snippets__create_snippet(
    NativePortType port_,
    String code,
    String? title,
    String? language,
    String? description,
    bool is_pinned,
    String? workspace_identifier,
    String? meta_workspace_id,
  ) => wasmModule.wire__crate__api__snippets__create_snippet(
    port_,
    code,
    title,
    language,
    description,
    is_pinned,
    workspace_identifier,
    meta_workspace_id,
  );

  void wire__crate__api__todo__create_todo(
    NativePortType port_,
    String title,
    String? description,
    String priority,
    String? due_date,
    String? workspace_identifier,
    String? meta_workspace_id,
  ) => wasmModule.wire__crate__api__todo__create_todo(
    port_,
    title,
    description,
    priority,
    due_date,
    workspace_identifier,
    meta_workspace_id,
  );

  void wire__crate__api__user_preference__create_user_preference(
    NativePortType port_,
    String first_name,
    String last_name,
    String email,
    String? meta_workspace_id,
  ) => wasmModule.wire__crate__api__user_preference__create_user_preference(
    port_,
    first_name,
    last_name,
    email,
    meta_workspace_id,
  );

  void wire__crate__api__workspaces__create_workspace(
    NativePortType port_,
    String name,
    String description,
  ) => wasmModule.wire__crate__api__workspaces__create_workspace(
    port_,
    name,
    description,
  );

  void wire__crate__api__bookmarks__delete_bookmark(
    NativePortType port_,
    String identifier,
    String? meta_workspace_id,
  ) => wasmModule.wire__crate__api__bookmarks__delete_bookmark(
    port_,
    identifier,
    meta_workspace_id,
  );

  void wire__crate__api__notes__delete_note(
    NativePortType port_,
    String identifier,
    String? meta_workspace_id,
  ) => wasmModule.wire__crate__api__notes__delete_note(
    port_,
    identifier,
    meta_workspace_id,
  );

  void wire__crate__api__reminders__delete_reminder(
    NativePortType port_,
    String identifier,
    String? meta_workspace_id,
  ) => wasmModule.wire__crate__api__reminders__delete_reminder(
    port_,
    identifier,
    meta_workspace_id,
  );

  void wire__crate__api__snippets__delete_snippet(
    NativePortType port_,
    String identifier,
    String? meta_workspace_id,
  ) => wasmModule.wire__crate__api__snippets__delete_snippet(
    port_,
    identifier,
    meta_workspace_id,
  );

  void wire__crate__api__todo__delete_todo(
    NativePortType port_,
    String identifier,
    String? meta_workspace_id,
  ) => wasmModule.wire__crate__api__todo__delete_todo(
    port_,
    identifier,
    meta_workspace_id,
  );

  void wire__crate__api__workspaces__delete_workspace(
    NativePortType port_,
    String identifier,
    String? meta_workspace_id,
  ) => wasmModule.wire__crate__api__workspaces__delete_workspace(
    port_,
    identifier,
    meta_workspace_id,
  );

  void wire__crate__api__bookmarks__duplicate_bookmark(
    NativePortType port_,
    String record_identifier,
    String previous_workspace_identifier,
    String target_workspace_identifier,
  ) => wasmModule.wire__crate__api__bookmarks__duplicate_bookmark(
    port_,
    record_identifier,
    previous_workspace_identifier,
    target_workspace_identifier,
  );

  void wire__crate__api__notes__duplicate_note(
    NativePortType port_,
    String record_identifier,
    String previous_workspace_identifier,
    String target_workspace_identifier,
  ) => wasmModule.wire__crate__api__notes__duplicate_note(
    port_,
    record_identifier,
    previous_workspace_identifier,
    target_workspace_identifier,
  );

  void wire__crate__api__reminders__duplicate_reminder(
    NativePortType port_,
    String record_identifier,
    String previous_workspace_identifier,
    String target_workspace_identifier,
  ) => wasmModule.wire__crate__api__reminders__duplicate_reminder(
    port_,
    record_identifier,
    previous_workspace_identifier,
    target_workspace_identifier,
  );

  void wire__crate__api__snippets__duplicate_snippet(
    NativePortType port_,
    String record_identifier,
    String previous_workspace_identifier,
    String target_workspace_identifier,
  ) => wasmModule.wire__crate__api__snippets__duplicate_snippet(
    port_,
    record_identifier,
    previous_workspace_identifier,
    target_workspace_identifier,
  );

  void wire__crate__api__todo__duplicate_todo(
    NativePortType port_,
    String record_identifier,
    String previous_workspace_identifier,
    String target_workspace_identifier,
  ) => wasmModule.wire__crate__api__todo__duplicate_todo(
    port_,
    record_identifier,
    previous_workspace_identifier,
    target_workspace_identifier,
  );

  void wire__crate__api__user_preference__duplicate_user_preference(
    NativePortType port_,
    String record_identifier,
    String previous_workspace_identifier,
    String target_workspace_identifier,
  ) => wasmModule.wire__crate__api__user_preference__duplicate_user_preference(
    port_,
    record_identifier,
    previous_workspace_identifier,
    target_workspace_identifier,
  );

  void wire__crate__api__bookmarks__get_all_bookmarks(
    NativePortType port_,
    String? meta_workspace_id,
  ) => wasmModule.wire__crate__api__bookmarks__get_all_bookmarks(
    port_,
    meta_workspace_id,
  );

  void wire__crate__api__notes__get_all_notes(
    NativePortType port_,
    String? meta_workspace_id,
  ) => wasmModule.wire__crate__api__notes__get_all_notes(
    port_,
    meta_workspace_id,
  );

  void wire__crate__api__recycle_bin__get_all_recycle_bin_entries(
    NativePortType port_,
    String? meta_workspace_id,
  ) => wasmModule.wire__crate__api__recycle_bin__get_all_recycle_bin_entries(
    port_,
    meta_workspace_id,
  );

  void wire__crate__api__reminders__get_all_reminders(
    NativePortType port_,
    String? meta_workspace_id,
  ) => wasmModule.wire__crate__api__reminders__get_all_reminders(
    port_,
    meta_workspace_id,
  );

  void wire__crate__api__snippets__get_all_snippets(
    NativePortType port_,
    String? meta_workspace_id,
  ) => wasmModule.wire__crate__api__snippets__get_all_snippets(
    port_,
    meta_workspace_id,
  );

  void wire__crate__api__todo__get_all_todos(
    NativePortType port_,
    String? meta_workspace_id,
  ) => wasmModule.wire__crate__api__todo__get_all_todos(
    port_,
    meta_workspace_id,
  );

  void wire__crate__api__bookmarks__get_bookmark(
    NativePortType port_,
    String identifier,
    String? meta_workspace_id,
  ) => wasmModule.wire__crate__api__bookmarks__get_bookmark(
    port_,
    identifier,
    meta_workspace_id,
  );

  void wire__crate__api__bookmarks__get_bookmarks_by_tag(
    NativePortType port_,
    String tag,
    String? meta_workspace_id,
  ) => wasmModule.wire__crate__api__bookmarks__get_bookmarks_by_tag(
    port_,
    tag,
    meta_workspace_id,
  );

  void wire__crate__api__notes__get_note(
    NativePortType port_,
    String identifier,
    String? meta_workspace_id,
  ) => wasmModule.wire__crate__api__notes__get_note(
    port_,
    identifier,
    meta_workspace_id,
  );

  void wire__crate__api__bookmarks__get_recently_added_bookmarks(
    NativePortType port_,
    String? meta_workspace_id,
  ) => wasmModule.wire__crate__api__bookmarks__get_recently_added_bookmarks(
    port_,
    meta_workspace_id,
  );

  void wire__crate__api__notes__get_recently_added_notes(
    NativePortType port_,
    String? meta_workspace_id,
  ) => wasmModule.wire__crate__api__notes__get_recently_added_notes(
    port_,
    meta_workspace_id,
  );

  void wire__crate__api__snippets__get_recently_added_snippets(
    NativePortType port_,
    String? meta_workspace_id,
  ) => wasmModule.wire__crate__api__snippets__get_recently_added_snippets(
    port_,
    meta_workspace_id,
  );

  void wire__crate__api__recycle_bin__get_recycle_bin_entries_by_type(
    NativePortType port_,
    String item_type,
    String? meta_workspace_id,
  ) =>
      wasmModule.wire__crate__api__recycle_bin__get_recycle_bin_entries_by_type(
        port_,
        item_type,
        meta_workspace_id,
      );

  void wire__crate__api__recycle_bin__get_recycle_bin_entry(
    NativePortType port_,
    String identifier,
    String? meta_workspace_id,
  ) => wasmModule.wire__crate__api__recycle_bin__get_recycle_bin_entry(
    port_,
    identifier,
    meta_workspace_id,
  );

  void wire__crate__api__reminders__get_reminder(
    NativePortType port_,
    String identifier,
    String? meta_workspace_id,
  ) => wasmModule.wire__crate__api__reminders__get_reminder(
    port_,
    identifier,
    meta_workspace_id,
  );

  void wire__crate__api__snippets__get_snippet(
    NativePortType port_,
    String identifier,
    String? meta_workspace_id,
  ) => wasmModule.wire__crate__api__snippets__get_snippet(
    port_,
    identifier,
    meta_workspace_id,
  );

  void wire__crate__api__todo__get_todo(
    NativePortType port_,
    String identifier,
    String? meta_workspace_id,
  ) => wasmModule.wire__crate__api__todo__get_todo(
    port_,
    identifier,
    meta_workspace_id,
  );

  void wire__crate__api__user_preference__get_user_preference(
    NativePortType port_,
    String? meta_workspace_id,
  ) => wasmModule.wire__crate__api__user_preference__get_user_preference(
    port_,
    meta_workspace_id,
  );

  void wire__crate__api__workspaces__get_workspace_by_id(
    NativePortType port_,
    String id,
  ) => wasmModule.wire__crate__api__workspaces__get_workspace_by_id(port_, id);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__simple__greet(String name) =>
      wasmModule.wire__crate__api__simple__greet(name);

  void wire__crate__api__simple__init_app(NativePortType port_) =>
      wasmModule.wire__crate__api__simple__init_app(port_);

  void wire__crate__api__simple__init_kernel(
    NativePortType port_,
    String database_url,
  ) => wasmModule.wire__crate__api__simple__init_kernel(port_, database_url);

  void wire__crate__api__workspaces__list_workspaces(NativePortType port_) =>
      wasmModule.wire__crate__api__workspaces__list_workspaces(port_);

  void wire__crate__api__todo__mark_todo_done(
    NativePortType port_,
    String identifier,
    bool done,
    String? meta_workspace_id,
  ) => wasmModule.wire__crate__api__todo__mark_todo_done(
    port_,
    identifier,
    done,
    meta_workspace_id,
  );

  void wire__crate__api__recycle_bin__purge_all_recycle_bin_entries(
    NativePortType port_,
    String? meta_workspace_id,
  ) => wasmModule.wire__crate__api__recycle_bin__purge_all_recycle_bin_entries(
    port_,
    meta_workspace_id,
  );

  void wire__crate__api__recycle_bin__purge_recycle_bin_entry(
    NativePortType port_,
    String identifier,
    String? meta_workspace_id,
  ) => wasmModule.wire__crate__api__recycle_bin__purge_recycle_bin_entry(
    port_,
    identifier,
    meta_workspace_id,
  );

  void wire__crate__api__bookmarks__transfer_bookmark(
    NativePortType port_,
    String record_identifier,
    String previous_workspace_identifier,
    String target_workspace_identifier,
  ) => wasmModule.wire__crate__api__bookmarks__transfer_bookmark(
    port_,
    record_identifier,
    previous_workspace_identifier,
    target_workspace_identifier,
  );

  void wire__crate__api__notes__transfer_note(
    NativePortType port_,
    String record_identifier,
    String previous_workspace_identifier,
    String target_workspace_identifier,
  ) => wasmModule.wire__crate__api__notes__transfer_note(
    port_,
    record_identifier,
    previous_workspace_identifier,
    target_workspace_identifier,
  );

  void wire__crate__api__reminders__transfer_reminder(
    NativePortType port_,
    String record_identifier,
    String previous_workspace_identifier,
    String target_workspace_identifier,
  ) => wasmModule.wire__crate__api__reminders__transfer_reminder(
    port_,
    record_identifier,
    previous_workspace_identifier,
    target_workspace_identifier,
  );

  void wire__crate__api__snippets__transfer_snippet(
    NativePortType port_,
    String record_identifier,
    String previous_workspace_identifier,
    String target_workspace_identifier,
  ) => wasmModule.wire__crate__api__snippets__transfer_snippet(
    port_,
    record_identifier,
    previous_workspace_identifier,
    target_workspace_identifier,
  );

  void wire__crate__api__todo__transfer_todo(
    NativePortType port_,
    String record_identifier,
    String previous_workspace_identifier,
    String target_workspace_identifier,
  ) => wasmModule.wire__crate__api__todo__transfer_todo(
    port_,
    record_identifier,
    previous_workspace_identifier,
    target_workspace_identifier,
  );

  void wire__crate__api__user_preference__transfer_user_preference(
    NativePortType port_,
    String record_identifier,
    String previous_workspace_identifier,
    String target_workspace_identifier,
  ) => wasmModule.wire__crate__api__user_preference__transfer_user_preference(
    port_,
    record_identifier,
    previous_workspace_identifier,
    target_workspace_identifier,
  );

  void wire__crate__api__bookmarks__update_bookmark(
    NativePortType port_,
    String identifier,
    String? title,
    String? url,
    String? tag,
    String? meta_workspace_id,
  ) => wasmModule.wire__crate__api__bookmarks__update_bookmark(
    port_,
    identifier,
    title,
    url,
    tag,
    meta_workspace_id,
  );

  void wire__crate__api__notes__update_note(
    NativePortType port_,
    String identifier,
    String? title,
    String? content,
    JSAny? categories,
    String? meta_workspace_id,
  ) => wasmModule.wire__crate__api__notes__update_note(
    port_,
    identifier,
    title,
    content,
    categories,
    meta_workspace_id,
  );

  void wire__crate__api__reminders__update_reminder(
    NativePortType port_,
    String identifier,
    String? title,
    String? description,
    String? remind_at,
    bool? recurring,
    String? recurrence_rule,
    String? alarm_sound,
    String? meta_workspace_id,
  ) => wasmModule.wire__crate__api__reminders__update_reminder(
    port_,
    identifier,
    title,
    description,
    remind_at,
    recurring,
    recurrence_rule,
    alarm_sound,
    meta_workspace_id,
  );

  void wire__crate__api__snippets__update_snippet(
    NativePortType port_,
    String identifier,
    String? title,
    String? language,
    String? code,
    String? description,
    bool? is_pinned,
    String? meta_workspace_id,
  ) => wasmModule.wire__crate__api__snippets__update_snippet(
    port_,
    identifier,
    title,
    language,
    code,
    description,
    is_pinned,
    meta_workspace_id,
  );

  void wire__crate__api__todo__update_todo(
    NativePortType port_,
    String identifier,
    String? title,
    String? description,
    String? priority,
    String? due_date,
    String? meta_workspace_id,
  ) => wasmModule.wire__crate__api__todo__update_todo(
    port_,
    identifier,
    title,
    description,
    priority,
    due_date,
    meta_workspace_id,
  );

  void wire__crate__api__todo__update_todo_due_date(
    NativePortType port_,
    String identifier,
    String? due_date,
    String? meta_workspace_id,
  ) => wasmModule.wire__crate__api__todo__update_todo_due_date(
    port_,
    identifier,
    due_date,
    meta_workspace_id,
  );

  void wire__crate__api__user_preference__update_user_preference(
    NativePortType port_,
    String identifier,
    String? first_name,
    String? last_name,
    String? email,
    String? meta_workspace_id,
  ) => wasmModule.wire__crate__api__user_preference__update_user_preference(
    port_,
    identifier,
    first_name,
    last_name,
    email,
    meta_workspace_id,
  );

  void wire__crate__api__workspaces__update_workspace(
    NativePortType port_,
    String identifier,
    String? name,
    String? description,
    bool? is_default,
    bool? is_hidden,
  ) => wasmModule.wire__crate__api__workspaces__update_workspace(
    port_,
    identifier,
    name,
    description,
    is_default,
    is_hidden,
  );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void wire__crate__api__todo__change_todo_priority(
    NativePortType port_,
    String identifier,
    String priority,
    String? meta_workspace_id,
  );

  external void wire__crate__api__bookmarks__create_bookmark(
    NativePortType port_,
    String title,
    String url,
    String tag,
    String? workspace_identifier,
    String? meta_workspace_id,
  );

  external void wire__crate__api__notes__create_note(
    NativePortType port_,
    String title,
    String content,
    JSAny? categories,
    String? workspace_identifier,
    String? meta_workspace_id,
  );

  external void wire__crate__api__recycle_bin__create_recycle_bin_entry(
    NativePortType port_,
    String item_id,
    String item_type,
    String payload,
    String? meta_workspace_id,
  );

  external void wire__crate__api__reminders__create_reminder(
    NativePortType port_,
    String title,
    String? description,
    String remind_at,
    bool recurring,
    String? recurrence_rule,
    String? alarm_sound,
    String? workspace_identifier,
    String? meta_workspace_id,
  );

  external void wire__crate__api__snippets__create_snippet(
    NativePortType port_,
    String code,
    String? title,
    String? language,
    String? description,
    bool is_pinned,
    String? workspace_identifier,
    String? meta_workspace_id,
  );

  external void wire__crate__api__todo__create_todo(
    NativePortType port_,
    String title,
    String? description,
    String priority,
    String? due_date,
    String? workspace_identifier,
    String? meta_workspace_id,
  );

  external void wire__crate__api__user_preference__create_user_preference(
    NativePortType port_,
    String first_name,
    String last_name,
    String email,
    String? meta_workspace_id,
  );

  external void wire__crate__api__workspaces__create_workspace(
    NativePortType port_,
    String name,
    String description,
  );

  external void wire__crate__api__bookmarks__delete_bookmark(
    NativePortType port_,
    String identifier,
    String? meta_workspace_id,
  );

  external void wire__crate__api__notes__delete_note(
    NativePortType port_,
    String identifier,
    String? meta_workspace_id,
  );

  external void wire__crate__api__reminders__delete_reminder(
    NativePortType port_,
    String identifier,
    String? meta_workspace_id,
  );

  external void wire__crate__api__snippets__delete_snippet(
    NativePortType port_,
    String identifier,
    String? meta_workspace_id,
  );

  external void wire__crate__api__todo__delete_todo(
    NativePortType port_,
    String identifier,
    String? meta_workspace_id,
  );

  external void wire__crate__api__workspaces__delete_workspace(
    NativePortType port_,
    String identifier,
    String? meta_workspace_id,
  );

  external void wire__crate__api__bookmarks__duplicate_bookmark(
    NativePortType port_,
    String record_identifier,
    String previous_workspace_identifier,
    String target_workspace_identifier,
  );

  external void wire__crate__api__notes__duplicate_note(
    NativePortType port_,
    String record_identifier,
    String previous_workspace_identifier,
    String target_workspace_identifier,
  );

  external void wire__crate__api__reminders__duplicate_reminder(
    NativePortType port_,
    String record_identifier,
    String previous_workspace_identifier,
    String target_workspace_identifier,
  );

  external void wire__crate__api__snippets__duplicate_snippet(
    NativePortType port_,
    String record_identifier,
    String previous_workspace_identifier,
    String target_workspace_identifier,
  );

  external void wire__crate__api__todo__duplicate_todo(
    NativePortType port_,
    String record_identifier,
    String previous_workspace_identifier,
    String target_workspace_identifier,
  );

  external void wire__crate__api__user_preference__duplicate_user_preference(
    NativePortType port_,
    String record_identifier,
    String previous_workspace_identifier,
    String target_workspace_identifier,
  );

  external void wire__crate__api__bookmarks__get_all_bookmarks(
    NativePortType port_,
    String? meta_workspace_id,
  );

  external void wire__crate__api__notes__get_all_notes(
    NativePortType port_,
    String? meta_workspace_id,
  );

  external void wire__crate__api__recycle_bin__get_all_recycle_bin_entries(
    NativePortType port_,
    String? meta_workspace_id,
  );

  external void wire__crate__api__reminders__get_all_reminders(
    NativePortType port_,
    String? meta_workspace_id,
  );

  external void wire__crate__api__snippets__get_all_snippets(
    NativePortType port_,
    String? meta_workspace_id,
  );

  external void wire__crate__api__todo__get_all_todos(
    NativePortType port_,
    String? meta_workspace_id,
  );

  external void wire__crate__api__bookmarks__get_bookmark(
    NativePortType port_,
    String identifier,
    String? meta_workspace_id,
  );

  external void wire__crate__api__bookmarks__get_bookmarks_by_tag(
    NativePortType port_,
    String tag,
    String? meta_workspace_id,
  );

  external void wire__crate__api__notes__get_note(
    NativePortType port_,
    String identifier,
    String? meta_workspace_id,
  );

  external void wire__crate__api__bookmarks__get_recently_added_bookmarks(
    NativePortType port_,
    String? meta_workspace_id,
  );

  external void wire__crate__api__notes__get_recently_added_notes(
    NativePortType port_,
    String? meta_workspace_id,
  );

  external void wire__crate__api__snippets__get_recently_added_snippets(
    NativePortType port_,
    String? meta_workspace_id,
  );

  external void wire__crate__api__recycle_bin__get_recycle_bin_entries_by_type(
    NativePortType port_,
    String item_type,
    String? meta_workspace_id,
  );

  external void wire__crate__api__recycle_bin__get_recycle_bin_entry(
    NativePortType port_,
    String identifier,
    String? meta_workspace_id,
  );

  external void wire__crate__api__reminders__get_reminder(
    NativePortType port_,
    String identifier,
    String? meta_workspace_id,
  );

  external void wire__crate__api__snippets__get_snippet(
    NativePortType port_,
    String identifier,
    String? meta_workspace_id,
  );

  external void wire__crate__api__todo__get_todo(
    NativePortType port_,
    String identifier,
    String? meta_workspace_id,
  );

  external void wire__crate__api__user_preference__get_user_preference(
    NativePortType port_,
    String? meta_workspace_id,
  );

  external void wire__crate__api__workspaces__get_workspace_by_id(
    NativePortType port_,
    String id,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__simple__greet(String name);

  external void wire__crate__api__simple__init_app(NativePortType port_);

  external void wire__crate__api__simple__init_kernel(
    NativePortType port_,
    String database_url,
  );

  external void wire__crate__api__workspaces__list_workspaces(
    NativePortType port_,
  );

  external void wire__crate__api__todo__mark_todo_done(
    NativePortType port_,
    String identifier,
    bool done,
    String? meta_workspace_id,
  );

  external void wire__crate__api__recycle_bin__purge_all_recycle_bin_entries(
    NativePortType port_,
    String? meta_workspace_id,
  );

  external void wire__crate__api__recycle_bin__purge_recycle_bin_entry(
    NativePortType port_,
    String identifier,
    String? meta_workspace_id,
  );

  external void wire__crate__api__bookmarks__transfer_bookmark(
    NativePortType port_,
    String record_identifier,
    String previous_workspace_identifier,
    String target_workspace_identifier,
  );

  external void wire__crate__api__notes__transfer_note(
    NativePortType port_,
    String record_identifier,
    String previous_workspace_identifier,
    String target_workspace_identifier,
  );

  external void wire__crate__api__reminders__transfer_reminder(
    NativePortType port_,
    String record_identifier,
    String previous_workspace_identifier,
    String target_workspace_identifier,
  );

  external void wire__crate__api__snippets__transfer_snippet(
    NativePortType port_,
    String record_identifier,
    String previous_workspace_identifier,
    String target_workspace_identifier,
  );

  external void wire__crate__api__todo__transfer_todo(
    NativePortType port_,
    String record_identifier,
    String previous_workspace_identifier,
    String target_workspace_identifier,
  );

  external void wire__crate__api__user_preference__transfer_user_preference(
    NativePortType port_,
    String record_identifier,
    String previous_workspace_identifier,
    String target_workspace_identifier,
  );

  external void wire__crate__api__bookmarks__update_bookmark(
    NativePortType port_,
    String identifier,
    String? title,
    String? url,
    String? tag,
    String? meta_workspace_id,
  );

  external void wire__crate__api__notes__update_note(
    NativePortType port_,
    String identifier,
    String? title,
    String? content,
    JSAny? categories,
    String? meta_workspace_id,
  );

  external void wire__crate__api__reminders__update_reminder(
    NativePortType port_,
    String identifier,
    String? title,
    String? description,
    String? remind_at,
    bool? recurring,
    String? recurrence_rule,
    String? alarm_sound,
    String? meta_workspace_id,
  );

  external void wire__crate__api__snippets__update_snippet(
    NativePortType port_,
    String identifier,
    String? title,
    String? language,
    String? code,
    String? description,
    bool? is_pinned,
    String? meta_workspace_id,
  );

  external void wire__crate__api__todo__update_todo(
    NativePortType port_,
    String identifier,
    String? title,
    String? description,
    String? priority,
    String? due_date,
    String? meta_workspace_id,
  );

  external void wire__crate__api__todo__update_todo_due_date(
    NativePortType port_,
    String identifier,
    String? due_date,
    String? meta_workspace_id,
  );

  external void wire__crate__api__user_preference__update_user_preference(
    NativePortType port_,
    String identifier,
    String? first_name,
    String? last_name,
    String? email,
    String? meta_workspace_id,
  );

  external void wire__crate__api__workspaces__update_workspace(
    NativePortType port_,
    String identifier,
    String? name,
    String? description,
    bool? is_default,
    bool? is_hidden,
  );
}
