// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/bookmarks.dart';
import 'api/kernel.dart';
import 'api/notes.dart';
import 'api/recycle_bin.dart';
import 'api/reminders.dart';
import 'api/snippets.dart';
import 'api/todo.dart';
import 'api/user_preference.dart';
import 'api/workspaces.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiKernelInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 141276317;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_shurbs',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<String> crateApiTodoChangeTodoPriority({
    required String identifier,
    required String priority,
    String? metaWorkspaceId,
  });

  Future<String> crateApiBookmarksCreateBookmark({
    required String title,
    required String url,
    required String tag,
    String? workspaceIdentifier,
    String? metaWorkspaceId,
  });

  Future<String> crateApiNotesCreateNote({
    required String title,
    required String content,
    List<String>? categories,
    String? workspaceIdentifier,
    String? metaWorkspaceId,
  });

  Future<String> crateApiRecycleBinCreateRecycleBinEntry({
    required String itemId,
    required String itemType,
    required String payload,
    String? metaWorkspaceId,
  });

  Future<String> crateApiRemindersCreateReminder({
    required String title,
    String? description,
    required String remindAt,
    required bool recurring,
    String? recurrenceRule,
    String? alarmSound,
    String? workspaceIdentifier,
    String? metaWorkspaceId,
  });

  Future<String> crateApiSnippetsCreateSnippet({
    required String code,
    String? title,
    String? language,
    String? description,
    required bool isPinned,
    String? workspaceIdentifier,
    String? metaWorkspaceId,
  });

  Future<String> crateApiTodoCreateTodo({
    required String title,
    String? description,
    required String priority,
    String? dueDate,
    String? workspaceIdentifier,
    String? metaWorkspaceId,
  });

  Future<String> crateApiUserPreferenceCreateUserPreference({
    required String firstName,
    required String lastName,
    required String email,
    String? metaWorkspaceId,
  });

  Future<String> crateApiWorkspacesCreateWorkspace({
    required String name,
    required String description,
  });

  Future<void> crateApiBookmarksDeleteBookmark({
    required String identifier,
    String? metaWorkspaceId,
  });

  Future<void> crateApiNotesDeleteNote({
    required String identifier,
    String? metaWorkspaceId,
  });

  Future<void> crateApiRemindersDeleteReminder({
    required String identifier,
    String? metaWorkspaceId,
  });

  Future<void> crateApiSnippetsDeleteSnippet({
    required String identifier,
    String? metaWorkspaceId,
  });

  Future<void> crateApiTodoDeleteTodo({
    required String identifier,
    String? metaWorkspaceId,
  });

  Future<void> crateApiWorkspacesDeleteWorkspace({
    required String identifier,
    String? metaWorkspaceId,
  });

  Future<void> crateApiBookmarksDuplicateBookmark({
    required String recordIdentifier,
    required String previousWorkspaceIdentifier,
    required String targetWorkspaceIdentifier,
  });

  Future<void> crateApiNotesDuplicateNote({
    required String recordIdentifier,
    required String previousWorkspaceIdentifier,
    required String targetWorkspaceIdentifier,
  });

  Future<void> crateApiRemindersDuplicateReminder({
    required String recordIdentifier,
    required String previousWorkspaceIdentifier,
    required String targetWorkspaceIdentifier,
  });

  Future<void> crateApiSnippetsDuplicateSnippet({
    required String recordIdentifier,
    required String previousWorkspaceIdentifier,
    required String targetWorkspaceIdentifier,
  });

  Future<void> crateApiTodoDuplicateTodo({
    required String recordIdentifier,
    required String previousWorkspaceIdentifier,
    required String targetWorkspaceIdentifier,
  });

  Future<void> crateApiUserPreferenceDuplicateUserPreference({
    required String recordIdentifier,
    required String previousWorkspaceIdentifier,
    required String targetWorkspaceIdentifier,
  });

  Future<String> crateApiBookmarksGetAllBookmarks({String? metaWorkspaceId});

  Future<String> crateApiNotesGetAllNotes({String? metaWorkspaceId});

  Future<String> crateApiRecycleBinGetAllRecycleBinEntries({
    String? metaWorkspaceId,
  });

  Future<String> crateApiRemindersGetAllReminders({String? metaWorkspaceId});

  Future<String> crateApiSnippetsGetAllSnippets({String? metaWorkspaceId});

  Future<String> crateApiTodoGetAllTodos({String? metaWorkspaceId});

  Future<String?> crateApiBookmarksGetBookmark({
    required String identifier,
    String? metaWorkspaceId,
  });

  Future<String> crateApiBookmarksGetBookmarksByTag({
    required String tag,
    String? metaWorkspaceId,
  });

  Future<String?> crateApiNotesGetNote({
    required String identifier,
    String? metaWorkspaceId,
  });

  Future<String> crateApiBookmarksGetRecentlyAddedBookmarks({
    String? metaWorkspaceId,
  });

  Future<String> crateApiNotesGetRecentlyAddedNotes({String? metaWorkspaceId});

  Future<String> crateApiSnippetsGetRecentlyAddedSnippets({
    String? metaWorkspaceId,
  });

  Future<String> crateApiRecycleBinGetRecycleBinEntriesByType({
    required String itemType,
    String? metaWorkspaceId,
  });

  Future<String?> crateApiRecycleBinGetRecycleBinEntry({
    required String identifier,
    String? metaWorkspaceId,
  });

  Future<String?> crateApiRemindersGetReminder({
    required String identifier,
    String? metaWorkspaceId,
  });

  Future<String?> crateApiSnippetsGetSnippet({
    required String identifier,
    String? metaWorkspaceId,
  });

  Future<String?> crateApiTodoGetTodo({
    required String identifier,
    String? metaWorkspaceId,
  });

  Future<String?> crateApiUserPreferenceGetUserPreference({
    String? metaWorkspaceId,
  });

  Future<String> crateApiWorkspacesGetWorkspaceById({required String id});

  Future<void> crateApiKernelInitApp();

  Future<void> crateApiKernelInitKernel({required String databaseUrl});

  Future<String> crateApiWorkspacesListWorkspaces();

  Future<String> crateApiTodoMarkTodoDone({
    required String identifier,
    required bool done,
    String? metaWorkspaceId,
  });

  Future<void> crateApiRecycleBinPurgeAllRecycleBinEntries({
    String? metaWorkspaceId,
  });

  Future<void> crateApiRecycleBinPurgeRecycleBinEntry({
    required String identifier,
    String? metaWorkspaceId,
  });

  Future<void> crateApiBookmarksTransferBookmark({
    required String recordIdentifier,
    required String previousWorkspaceIdentifier,
    required String targetWorkspaceIdentifier,
  });

  Future<void> crateApiNotesTransferNote({
    required String recordIdentifier,
    required String previousWorkspaceIdentifier,
    required String targetWorkspaceIdentifier,
  });

  Future<void> crateApiRemindersTransferReminder({
    required String recordIdentifier,
    required String previousWorkspaceIdentifier,
    required String targetWorkspaceIdentifier,
  });

  Future<void> crateApiSnippetsTransferSnippet({
    required String recordIdentifier,
    required String previousWorkspaceIdentifier,
    required String targetWorkspaceIdentifier,
  });

  Future<void> crateApiTodoTransferTodo({
    required String recordIdentifier,
    required String previousWorkspaceIdentifier,
    required String targetWorkspaceIdentifier,
  });

  Future<void> crateApiUserPreferenceTransferUserPreference({
    required String recordIdentifier,
    required String previousWorkspaceIdentifier,
    required String targetWorkspaceIdentifier,
  });

  Future<String> crateApiBookmarksUpdateBookmark({
    required String identifier,
    String? title,
    String? url,
    String? tag,
    String? metaWorkspaceId,
  });

  Future<String> crateApiNotesUpdateNote({
    required String identifier,
    String? title,
    String? content,
    List<String>? categories,
    String? metaWorkspaceId,
  });

  Future<String> crateApiRemindersUpdateReminder({
    required String identifier,
    String? title,
    String? description,
    String? remindAt,
    bool? recurring,
    String? recurrenceRule,
    String? alarmSound,
    String? metaWorkspaceId,
  });

  Future<String> crateApiSnippetsUpdateSnippet({
    required String identifier,
    String? title,
    String? language,
    String? code,
    String? description,
    bool? isPinned,
    String? metaWorkspaceId,
  });

  Future<String> crateApiTodoUpdateTodo({
    required String identifier,
    String? title,
    String? description,
    String? priority,
    String? dueDate,
    String? metaWorkspaceId,
  });

  Future<String> crateApiTodoUpdateTodoDueDate({
    required String identifier,
    String? dueDate,
    String? metaWorkspaceId,
  });

  Future<String> crateApiUserPreferenceUpdateUserPreference({
    required String identifier,
    String? firstName,
    String? lastName,
    String? email,
    String? metaWorkspaceId,
  });

  Future<String> crateApiWorkspacesUpdateWorkspace({
    required String identifier,
    String? name,
    String? description,
    bool? isDefault,
    bool? isHidden,
    bool? isSecured,
    String? password,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> crateApiTodoChangeTodoPriority({
    required String identifier,
    required String priority,
    String? metaWorkspaceId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(identifier);
          var arg1 = cst_encode_String(priority);
          var arg2 = cst_encode_opt_String(metaWorkspaceId);
          return wire.wire__crate__api__todo__change_todo_priority(
            port_,
            arg0,
            arg1,
            arg2,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiTodoChangeTodoPriorityConstMeta,
        argValues: [identifier, priority, metaWorkspaceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTodoChangeTodoPriorityConstMeta =>
      const TaskConstMeta(
        debugName: "change_todo_priority",
        argNames: ["identifier", "priority", "metaWorkspaceId"],
      );

  @override
  Future<String> crateApiBookmarksCreateBookmark({
    required String title,
    required String url,
    required String tag,
    String? workspaceIdentifier,
    String? metaWorkspaceId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(title);
          var arg1 = cst_encode_String(url);
          var arg2 = cst_encode_String(tag);
          var arg3 = cst_encode_opt_String(workspaceIdentifier);
          var arg4 = cst_encode_opt_String(metaWorkspaceId);
          return wire.wire__crate__api__bookmarks__create_bookmark(
            port_,
            arg0,
            arg1,
            arg2,
            arg3,
            arg4,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiBookmarksCreateBookmarkConstMeta,
        argValues: [title, url, tag, workspaceIdentifier, metaWorkspaceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBookmarksCreateBookmarkConstMeta =>
      const TaskConstMeta(
        debugName: "create_bookmark",
        argNames: [
          "title",
          "url",
          "tag",
          "workspaceIdentifier",
          "metaWorkspaceId",
        ],
      );

  @override
  Future<String> crateApiNotesCreateNote({
    required String title,
    required String content,
    List<String>? categories,
    String? workspaceIdentifier,
    String? metaWorkspaceId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(title);
          var arg1 = cst_encode_String(content);
          var arg2 = cst_encode_opt_list_String(categories);
          var arg3 = cst_encode_opt_String(workspaceIdentifier);
          var arg4 = cst_encode_opt_String(metaWorkspaceId);
          return wire.wire__crate__api__notes__create_note(
            port_,
            arg0,
            arg1,
            arg2,
            arg3,
            arg4,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiNotesCreateNoteConstMeta,
        argValues: [
          title,
          content,
          categories,
          workspaceIdentifier,
          metaWorkspaceId,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNotesCreateNoteConstMeta => const TaskConstMeta(
    debugName: "create_note",
    argNames: [
      "title",
      "content",
      "categories",
      "workspaceIdentifier",
      "metaWorkspaceId",
    ],
  );

  @override
  Future<String> crateApiRecycleBinCreateRecycleBinEntry({
    required String itemId,
    required String itemType,
    required String payload,
    String? metaWorkspaceId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(itemId);
          var arg1 = cst_encode_String(itemType);
          var arg2 = cst_encode_String(payload);
          var arg3 = cst_encode_opt_String(metaWorkspaceId);
          return wire.wire__crate__api__recycle_bin__create_recycle_bin_entry(
            port_,
            arg0,
            arg1,
            arg2,
            arg3,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiRecycleBinCreateRecycleBinEntryConstMeta,
        argValues: [itemId, itemType, payload, metaWorkspaceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRecycleBinCreateRecycleBinEntryConstMeta =>
      const TaskConstMeta(
        debugName: "create_recycle_bin_entry",
        argNames: ["itemId", "itemType", "payload", "metaWorkspaceId"],
      );

  @override
  Future<String> crateApiRemindersCreateReminder({
    required String title,
    String? description,
    required String remindAt,
    required bool recurring,
    String? recurrenceRule,
    String? alarmSound,
    String? workspaceIdentifier,
    String? metaWorkspaceId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(title);
          var arg1 = cst_encode_opt_String(description);
          var arg2 = cst_encode_String(remindAt);
          var arg3 = cst_encode_bool(recurring);
          var arg4 = cst_encode_opt_String(recurrenceRule);
          var arg5 = cst_encode_opt_String(alarmSound);
          var arg6 = cst_encode_opt_String(workspaceIdentifier);
          var arg7 = cst_encode_opt_String(metaWorkspaceId);
          return wire.wire__crate__api__reminders__create_reminder(
            port_,
            arg0,
            arg1,
            arg2,
            arg3,
            arg4,
            arg5,
            arg6,
            arg7,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiRemindersCreateReminderConstMeta,
        argValues: [
          title,
          description,
          remindAt,
          recurring,
          recurrenceRule,
          alarmSound,
          workspaceIdentifier,
          metaWorkspaceId,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRemindersCreateReminderConstMeta =>
      const TaskConstMeta(
        debugName: "create_reminder",
        argNames: [
          "title",
          "description",
          "remindAt",
          "recurring",
          "recurrenceRule",
          "alarmSound",
          "workspaceIdentifier",
          "metaWorkspaceId",
        ],
      );

  @override
  Future<String> crateApiSnippetsCreateSnippet({
    required String code,
    String? title,
    String? language,
    String? description,
    required bool isPinned,
    String? workspaceIdentifier,
    String? metaWorkspaceId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(code);
          var arg1 = cst_encode_opt_String(title);
          var arg2 = cst_encode_opt_String(language);
          var arg3 = cst_encode_opt_String(description);
          var arg4 = cst_encode_bool(isPinned);
          var arg5 = cst_encode_opt_String(workspaceIdentifier);
          var arg6 = cst_encode_opt_String(metaWorkspaceId);
          return wire.wire__crate__api__snippets__create_snippet(
            port_,
            arg0,
            arg1,
            arg2,
            arg3,
            arg4,
            arg5,
            arg6,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiSnippetsCreateSnippetConstMeta,
        argValues: [
          code,
          title,
          language,
          description,
          isPinned,
          workspaceIdentifier,
          metaWorkspaceId,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSnippetsCreateSnippetConstMeta =>
      const TaskConstMeta(
        debugName: "create_snippet",
        argNames: [
          "code",
          "title",
          "language",
          "description",
          "isPinned",
          "workspaceIdentifier",
          "metaWorkspaceId",
        ],
      );

  @override
  Future<String> crateApiTodoCreateTodo({
    required String title,
    String? description,
    required String priority,
    String? dueDate,
    String? workspaceIdentifier,
    String? metaWorkspaceId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(title);
          var arg1 = cst_encode_opt_String(description);
          var arg2 = cst_encode_String(priority);
          var arg3 = cst_encode_opt_String(dueDate);
          var arg4 = cst_encode_opt_String(workspaceIdentifier);
          var arg5 = cst_encode_opt_String(metaWorkspaceId);
          return wire.wire__crate__api__todo__create_todo(
            port_,
            arg0,
            arg1,
            arg2,
            arg3,
            arg4,
            arg5,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiTodoCreateTodoConstMeta,
        argValues: [
          title,
          description,
          priority,
          dueDate,
          workspaceIdentifier,
          metaWorkspaceId,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTodoCreateTodoConstMeta => const TaskConstMeta(
    debugName: "create_todo",
    argNames: [
      "title",
      "description",
      "priority",
      "dueDate",
      "workspaceIdentifier",
      "metaWorkspaceId",
    ],
  );

  @override
  Future<String> crateApiUserPreferenceCreateUserPreference({
    required String firstName,
    required String lastName,
    required String email,
    String? metaWorkspaceId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(firstName);
          var arg1 = cst_encode_String(lastName);
          var arg2 = cst_encode_String(email);
          var arg3 = cst_encode_opt_String(metaWorkspaceId);
          return wire.wire__crate__api__user_preference__create_user_preference(
            port_,
            arg0,
            arg1,
            arg2,
            arg3,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiUserPreferenceCreateUserPreferenceConstMeta,
        argValues: [firstName, lastName, email, metaWorkspaceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUserPreferenceCreateUserPreferenceConstMeta =>
      const TaskConstMeta(
        debugName: "create_user_preference",
        argNames: ["firstName", "lastName", "email", "metaWorkspaceId"],
      );

  @override
  Future<String> crateApiWorkspacesCreateWorkspace({
    required String name,
    required String description,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(name);
          var arg1 = cst_encode_String(description);
          return wire.wire__crate__api__workspaces__create_workspace(
            port_,
            arg0,
            arg1,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiWorkspacesCreateWorkspaceConstMeta,
        argValues: [name, description],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWorkspacesCreateWorkspaceConstMeta =>
      const TaskConstMeta(
        debugName: "create_workspace",
        argNames: ["name", "description"],
      );

  @override
  Future<void> crateApiBookmarksDeleteBookmark({
    required String identifier,
    String? metaWorkspaceId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(identifier);
          var arg1 = cst_encode_opt_String(metaWorkspaceId);
          return wire.wire__crate__api__bookmarks__delete_bookmark(
            port_,
            arg0,
            arg1,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiBookmarksDeleteBookmarkConstMeta,
        argValues: [identifier, metaWorkspaceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBookmarksDeleteBookmarkConstMeta =>
      const TaskConstMeta(
        debugName: "delete_bookmark",
        argNames: ["identifier", "metaWorkspaceId"],
      );

  @override
  Future<void> crateApiNotesDeleteNote({
    required String identifier,
    String? metaWorkspaceId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(identifier);
          var arg1 = cst_encode_opt_String(metaWorkspaceId);
          return wire.wire__crate__api__notes__delete_note(port_, arg0, arg1);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiNotesDeleteNoteConstMeta,
        argValues: [identifier, metaWorkspaceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNotesDeleteNoteConstMeta => const TaskConstMeta(
    debugName: "delete_note",
    argNames: ["identifier", "metaWorkspaceId"],
  );

  @override
  Future<void> crateApiRemindersDeleteReminder({
    required String identifier,
    String? metaWorkspaceId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(identifier);
          var arg1 = cst_encode_opt_String(metaWorkspaceId);
          return wire.wire__crate__api__reminders__delete_reminder(
            port_,
            arg0,
            arg1,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiRemindersDeleteReminderConstMeta,
        argValues: [identifier, metaWorkspaceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRemindersDeleteReminderConstMeta =>
      const TaskConstMeta(
        debugName: "delete_reminder",
        argNames: ["identifier", "metaWorkspaceId"],
      );

  @override
  Future<void> crateApiSnippetsDeleteSnippet({
    required String identifier,
    String? metaWorkspaceId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(identifier);
          var arg1 = cst_encode_opt_String(metaWorkspaceId);
          return wire.wire__crate__api__snippets__delete_snippet(
            port_,
            arg0,
            arg1,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiSnippetsDeleteSnippetConstMeta,
        argValues: [identifier, metaWorkspaceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSnippetsDeleteSnippetConstMeta =>
      const TaskConstMeta(
        debugName: "delete_snippet",
        argNames: ["identifier", "metaWorkspaceId"],
      );

  @override
  Future<void> crateApiTodoDeleteTodo({
    required String identifier,
    String? metaWorkspaceId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(identifier);
          var arg1 = cst_encode_opt_String(metaWorkspaceId);
          return wire.wire__crate__api__todo__delete_todo(port_, arg0, arg1);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiTodoDeleteTodoConstMeta,
        argValues: [identifier, metaWorkspaceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTodoDeleteTodoConstMeta => const TaskConstMeta(
    debugName: "delete_todo",
    argNames: ["identifier", "metaWorkspaceId"],
  );

  @override
  Future<void> crateApiWorkspacesDeleteWorkspace({
    required String identifier,
    String? metaWorkspaceId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(identifier);
          var arg1 = cst_encode_opt_String(metaWorkspaceId);
          return wire.wire__crate__api__workspaces__delete_workspace(
            port_,
            arg0,
            arg1,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiWorkspacesDeleteWorkspaceConstMeta,
        argValues: [identifier, metaWorkspaceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWorkspacesDeleteWorkspaceConstMeta =>
      const TaskConstMeta(
        debugName: "delete_workspace",
        argNames: ["identifier", "metaWorkspaceId"],
      );

  @override
  Future<void> crateApiBookmarksDuplicateBookmark({
    required String recordIdentifier,
    required String previousWorkspaceIdentifier,
    required String targetWorkspaceIdentifier,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(recordIdentifier);
          var arg1 = cst_encode_String(previousWorkspaceIdentifier);
          var arg2 = cst_encode_String(targetWorkspaceIdentifier);
          return wire.wire__crate__api__bookmarks__duplicate_bookmark(
            port_,
            arg0,
            arg1,
            arg2,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiBookmarksDuplicateBookmarkConstMeta,
        argValues: [
          recordIdentifier,
          previousWorkspaceIdentifier,
          targetWorkspaceIdentifier,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBookmarksDuplicateBookmarkConstMeta =>
      const TaskConstMeta(
        debugName: "duplicate_bookmark",
        argNames: [
          "recordIdentifier",
          "previousWorkspaceIdentifier",
          "targetWorkspaceIdentifier",
        ],
      );

  @override
  Future<void> crateApiNotesDuplicateNote({
    required String recordIdentifier,
    required String previousWorkspaceIdentifier,
    required String targetWorkspaceIdentifier,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(recordIdentifier);
          var arg1 = cst_encode_String(previousWorkspaceIdentifier);
          var arg2 = cst_encode_String(targetWorkspaceIdentifier);
          return wire.wire__crate__api__notes__duplicate_note(
            port_,
            arg0,
            arg1,
            arg2,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiNotesDuplicateNoteConstMeta,
        argValues: [
          recordIdentifier,
          previousWorkspaceIdentifier,
          targetWorkspaceIdentifier,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNotesDuplicateNoteConstMeta => const TaskConstMeta(
    debugName: "duplicate_note",
    argNames: [
      "recordIdentifier",
      "previousWorkspaceIdentifier",
      "targetWorkspaceIdentifier",
    ],
  );

  @override
  Future<void> crateApiRemindersDuplicateReminder({
    required String recordIdentifier,
    required String previousWorkspaceIdentifier,
    required String targetWorkspaceIdentifier,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(recordIdentifier);
          var arg1 = cst_encode_String(previousWorkspaceIdentifier);
          var arg2 = cst_encode_String(targetWorkspaceIdentifier);
          return wire.wire__crate__api__reminders__duplicate_reminder(
            port_,
            arg0,
            arg1,
            arg2,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiRemindersDuplicateReminderConstMeta,
        argValues: [
          recordIdentifier,
          previousWorkspaceIdentifier,
          targetWorkspaceIdentifier,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRemindersDuplicateReminderConstMeta =>
      const TaskConstMeta(
        debugName: "duplicate_reminder",
        argNames: [
          "recordIdentifier",
          "previousWorkspaceIdentifier",
          "targetWorkspaceIdentifier",
        ],
      );

  @override
  Future<void> crateApiSnippetsDuplicateSnippet({
    required String recordIdentifier,
    required String previousWorkspaceIdentifier,
    required String targetWorkspaceIdentifier,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(recordIdentifier);
          var arg1 = cst_encode_String(previousWorkspaceIdentifier);
          var arg2 = cst_encode_String(targetWorkspaceIdentifier);
          return wire.wire__crate__api__snippets__duplicate_snippet(
            port_,
            arg0,
            arg1,
            arg2,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiSnippetsDuplicateSnippetConstMeta,
        argValues: [
          recordIdentifier,
          previousWorkspaceIdentifier,
          targetWorkspaceIdentifier,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSnippetsDuplicateSnippetConstMeta =>
      const TaskConstMeta(
        debugName: "duplicate_snippet",
        argNames: [
          "recordIdentifier",
          "previousWorkspaceIdentifier",
          "targetWorkspaceIdentifier",
        ],
      );

  @override
  Future<void> crateApiTodoDuplicateTodo({
    required String recordIdentifier,
    required String previousWorkspaceIdentifier,
    required String targetWorkspaceIdentifier,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(recordIdentifier);
          var arg1 = cst_encode_String(previousWorkspaceIdentifier);
          var arg2 = cst_encode_String(targetWorkspaceIdentifier);
          return wire.wire__crate__api__todo__duplicate_todo(
            port_,
            arg0,
            arg1,
            arg2,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiTodoDuplicateTodoConstMeta,
        argValues: [
          recordIdentifier,
          previousWorkspaceIdentifier,
          targetWorkspaceIdentifier,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTodoDuplicateTodoConstMeta => const TaskConstMeta(
    debugName: "duplicate_todo",
    argNames: [
      "recordIdentifier",
      "previousWorkspaceIdentifier",
      "targetWorkspaceIdentifier",
    ],
  );

  @override
  Future<void> crateApiUserPreferenceDuplicateUserPreference({
    required String recordIdentifier,
    required String previousWorkspaceIdentifier,
    required String targetWorkspaceIdentifier,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(recordIdentifier);
          var arg1 = cst_encode_String(previousWorkspaceIdentifier);
          var arg2 = cst_encode_String(targetWorkspaceIdentifier);
          return wire
              .wire__crate__api__user_preference__duplicate_user_preference(
                port_,
                arg0,
                arg1,
                arg2,
              );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiUserPreferenceDuplicateUserPreferenceConstMeta,
        argValues: [
          recordIdentifier,
          previousWorkspaceIdentifier,
          targetWorkspaceIdentifier,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUserPreferenceDuplicateUserPreferenceConstMeta =>
      const TaskConstMeta(
        debugName: "duplicate_user_preference",
        argNames: [
          "recordIdentifier",
          "previousWorkspaceIdentifier",
          "targetWorkspaceIdentifier",
        ],
      );

  @override
  Future<String> crateApiBookmarksGetAllBookmarks({String? metaWorkspaceId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_opt_String(metaWorkspaceId);
          return wire.wire__crate__api__bookmarks__get_all_bookmarks(
            port_,
            arg0,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiBookmarksGetAllBookmarksConstMeta,
        argValues: [metaWorkspaceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBookmarksGetAllBookmarksConstMeta =>
      const TaskConstMeta(
        debugName: "get_all_bookmarks",
        argNames: ["metaWorkspaceId"],
      );

  @override
  Future<String> crateApiNotesGetAllNotes({String? metaWorkspaceId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_opt_String(metaWorkspaceId);
          return wire.wire__crate__api__notes__get_all_notes(port_, arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiNotesGetAllNotesConstMeta,
        argValues: [metaWorkspaceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNotesGetAllNotesConstMeta => const TaskConstMeta(
    debugName: "get_all_notes",
    argNames: ["metaWorkspaceId"],
  );

  @override
  Future<String> crateApiRecycleBinGetAllRecycleBinEntries({
    String? metaWorkspaceId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_opt_String(metaWorkspaceId);
          return wire
              .wire__crate__api__recycle_bin__get_all_recycle_bin_entries(
                port_,
                arg0,
              );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiRecycleBinGetAllRecycleBinEntriesConstMeta,
        argValues: [metaWorkspaceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRecycleBinGetAllRecycleBinEntriesConstMeta =>
      const TaskConstMeta(
        debugName: "get_all_recycle_bin_entries",
        argNames: ["metaWorkspaceId"],
      );

  @override
  Future<String> crateApiRemindersGetAllReminders({String? metaWorkspaceId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_opt_String(metaWorkspaceId);
          return wire.wire__crate__api__reminders__get_all_reminders(
            port_,
            arg0,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiRemindersGetAllRemindersConstMeta,
        argValues: [metaWorkspaceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRemindersGetAllRemindersConstMeta =>
      const TaskConstMeta(
        debugName: "get_all_reminders",
        argNames: ["metaWorkspaceId"],
      );

  @override
  Future<String> crateApiSnippetsGetAllSnippets({String? metaWorkspaceId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_opt_String(metaWorkspaceId);
          return wire.wire__crate__api__snippets__get_all_snippets(port_, arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiSnippetsGetAllSnippetsConstMeta,
        argValues: [metaWorkspaceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSnippetsGetAllSnippetsConstMeta =>
      const TaskConstMeta(
        debugName: "get_all_snippets",
        argNames: ["metaWorkspaceId"],
      );

  @override
  Future<String> crateApiTodoGetAllTodos({String? metaWorkspaceId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_opt_String(metaWorkspaceId);
          return wire.wire__crate__api__todo__get_all_todos(port_, arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiTodoGetAllTodosConstMeta,
        argValues: [metaWorkspaceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTodoGetAllTodosConstMeta => const TaskConstMeta(
    debugName: "get_all_todos",
    argNames: ["metaWorkspaceId"],
  );

  @override
  Future<String?> crateApiBookmarksGetBookmark({
    required String identifier,
    String? metaWorkspaceId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(identifier);
          var arg1 = cst_encode_opt_String(metaWorkspaceId);
          return wire.wire__crate__api__bookmarks__get_bookmark(
            port_,
            arg0,
            arg1,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_opt_String,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiBookmarksGetBookmarkConstMeta,
        argValues: [identifier, metaWorkspaceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBookmarksGetBookmarkConstMeta =>
      const TaskConstMeta(
        debugName: "get_bookmark",
        argNames: ["identifier", "metaWorkspaceId"],
      );

  @override
  Future<String> crateApiBookmarksGetBookmarksByTag({
    required String tag,
    String? metaWorkspaceId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(tag);
          var arg1 = cst_encode_opt_String(metaWorkspaceId);
          return wire.wire__crate__api__bookmarks__get_bookmarks_by_tag(
            port_,
            arg0,
            arg1,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiBookmarksGetBookmarksByTagConstMeta,
        argValues: [tag, metaWorkspaceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBookmarksGetBookmarksByTagConstMeta =>
      const TaskConstMeta(
        debugName: "get_bookmarks_by_tag",
        argNames: ["tag", "metaWorkspaceId"],
      );

  @override
  Future<String?> crateApiNotesGetNote({
    required String identifier,
    String? metaWorkspaceId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(identifier);
          var arg1 = cst_encode_opt_String(metaWorkspaceId);
          return wire.wire__crate__api__notes__get_note(port_, arg0, arg1);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_opt_String,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiNotesGetNoteConstMeta,
        argValues: [identifier, metaWorkspaceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNotesGetNoteConstMeta => const TaskConstMeta(
    debugName: "get_note",
    argNames: ["identifier", "metaWorkspaceId"],
  );

  @override
  Future<String> crateApiBookmarksGetRecentlyAddedBookmarks({
    String? metaWorkspaceId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_opt_String(metaWorkspaceId);
          return wire.wire__crate__api__bookmarks__get_recently_added_bookmarks(
            port_,
            arg0,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiBookmarksGetRecentlyAddedBookmarksConstMeta,
        argValues: [metaWorkspaceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBookmarksGetRecentlyAddedBookmarksConstMeta =>
      const TaskConstMeta(
        debugName: "get_recently_added_bookmarks",
        argNames: ["metaWorkspaceId"],
      );

  @override
  Future<String> crateApiNotesGetRecentlyAddedNotes({String? metaWorkspaceId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_opt_String(metaWorkspaceId);
          return wire.wire__crate__api__notes__get_recently_added_notes(
            port_,
            arg0,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiNotesGetRecentlyAddedNotesConstMeta,
        argValues: [metaWorkspaceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNotesGetRecentlyAddedNotesConstMeta =>
      const TaskConstMeta(
        debugName: "get_recently_added_notes",
        argNames: ["metaWorkspaceId"],
      );

  @override
  Future<String> crateApiSnippetsGetRecentlyAddedSnippets({
    String? metaWorkspaceId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_opt_String(metaWorkspaceId);
          return wire.wire__crate__api__snippets__get_recently_added_snippets(
            port_,
            arg0,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiSnippetsGetRecentlyAddedSnippetsConstMeta,
        argValues: [metaWorkspaceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSnippetsGetRecentlyAddedSnippetsConstMeta =>
      const TaskConstMeta(
        debugName: "get_recently_added_snippets",
        argNames: ["metaWorkspaceId"],
      );

  @override
  Future<String> crateApiRecycleBinGetRecycleBinEntriesByType({
    required String itemType,
    String? metaWorkspaceId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(itemType);
          var arg1 = cst_encode_opt_String(metaWorkspaceId);
          return wire
              .wire__crate__api__recycle_bin__get_recycle_bin_entries_by_type(
                port_,
                arg0,
                arg1,
              );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiRecycleBinGetRecycleBinEntriesByTypeConstMeta,
        argValues: [itemType, metaWorkspaceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRecycleBinGetRecycleBinEntriesByTypeConstMeta =>
      const TaskConstMeta(
        debugName: "get_recycle_bin_entries_by_type",
        argNames: ["itemType", "metaWorkspaceId"],
      );

  @override
  Future<String?> crateApiRecycleBinGetRecycleBinEntry({
    required String identifier,
    String? metaWorkspaceId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(identifier);
          var arg1 = cst_encode_opt_String(metaWorkspaceId);
          return wire.wire__crate__api__recycle_bin__get_recycle_bin_entry(
            port_,
            arg0,
            arg1,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_opt_String,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiRecycleBinGetRecycleBinEntryConstMeta,
        argValues: [identifier, metaWorkspaceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRecycleBinGetRecycleBinEntryConstMeta =>
      const TaskConstMeta(
        debugName: "get_recycle_bin_entry",
        argNames: ["identifier", "metaWorkspaceId"],
      );

  @override
  Future<String?> crateApiRemindersGetReminder({
    required String identifier,
    String? metaWorkspaceId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(identifier);
          var arg1 = cst_encode_opt_String(metaWorkspaceId);
          return wire.wire__crate__api__reminders__get_reminder(
            port_,
            arg0,
            arg1,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_opt_String,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiRemindersGetReminderConstMeta,
        argValues: [identifier, metaWorkspaceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRemindersGetReminderConstMeta =>
      const TaskConstMeta(
        debugName: "get_reminder",
        argNames: ["identifier", "metaWorkspaceId"],
      );

  @override
  Future<String?> crateApiSnippetsGetSnippet({
    required String identifier,
    String? metaWorkspaceId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(identifier);
          var arg1 = cst_encode_opt_String(metaWorkspaceId);
          return wire.wire__crate__api__snippets__get_snippet(
            port_,
            arg0,
            arg1,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_opt_String,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiSnippetsGetSnippetConstMeta,
        argValues: [identifier, metaWorkspaceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSnippetsGetSnippetConstMeta => const TaskConstMeta(
    debugName: "get_snippet",
    argNames: ["identifier", "metaWorkspaceId"],
  );

  @override
  Future<String?> crateApiTodoGetTodo({
    required String identifier,
    String? metaWorkspaceId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(identifier);
          var arg1 = cst_encode_opt_String(metaWorkspaceId);
          return wire.wire__crate__api__todo__get_todo(port_, arg0, arg1);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_opt_String,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiTodoGetTodoConstMeta,
        argValues: [identifier, metaWorkspaceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTodoGetTodoConstMeta => const TaskConstMeta(
    debugName: "get_todo",
    argNames: ["identifier", "metaWorkspaceId"],
  );

  @override
  Future<String?> crateApiUserPreferenceGetUserPreference({
    String? metaWorkspaceId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_opt_String(metaWorkspaceId);
          return wire.wire__crate__api__user_preference__get_user_preference(
            port_,
            arg0,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_opt_String,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiUserPreferenceGetUserPreferenceConstMeta,
        argValues: [metaWorkspaceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUserPreferenceGetUserPreferenceConstMeta =>
      const TaskConstMeta(
        debugName: "get_user_preference",
        argNames: ["metaWorkspaceId"],
      );

  @override
  Future<String> crateApiWorkspacesGetWorkspaceById({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(id);
          return wire.wire__crate__api__workspaces__get_workspace_by_id(
            port_,
            arg0,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiWorkspacesGetWorkspaceByIdConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWorkspacesGetWorkspaceByIdConstMeta =>
      const TaskConstMeta(debugName: "get_workspace_by_id", argNames: ["id"]);

  @override
  Future<void> crateApiKernelInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          return wire.wire__crate__api__kernel__init_app(port_);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiKernelInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKernelInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<void> crateApiKernelInitKernel({required String databaseUrl}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(databaseUrl);
          return wire.wire__crate__api__kernel__init_kernel(port_, arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiKernelInitKernelConstMeta,
        argValues: [databaseUrl],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKernelInitKernelConstMeta =>
      const TaskConstMeta(debugName: "init_kernel", argNames: ["databaseUrl"]);

  @override
  Future<String> crateApiWorkspacesListWorkspaces() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          return wire.wire__crate__api__workspaces__list_workspaces(port_);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiWorkspacesListWorkspacesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWorkspacesListWorkspacesConstMeta =>
      const TaskConstMeta(debugName: "list_workspaces", argNames: []);

  @override
  Future<String> crateApiTodoMarkTodoDone({
    required String identifier,
    required bool done,
    String? metaWorkspaceId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(identifier);
          var arg1 = cst_encode_bool(done);
          var arg2 = cst_encode_opt_String(metaWorkspaceId);
          return wire.wire__crate__api__todo__mark_todo_done(
            port_,
            arg0,
            arg1,
            arg2,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiTodoMarkTodoDoneConstMeta,
        argValues: [identifier, done, metaWorkspaceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTodoMarkTodoDoneConstMeta => const TaskConstMeta(
    debugName: "mark_todo_done",
    argNames: ["identifier", "done", "metaWorkspaceId"],
  );

  @override
  Future<void> crateApiRecycleBinPurgeAllRecycleBinEntries({
    String? metaWorkspaceId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_opt_String(metaWorkspaceId);
          return wire
              .wire__crate__api__recycle_bin__purge_all_recycle_bin_entries(
                port_,
                arg0,
              );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiRecycleBinPurgeAllRecycleBinEntriesConstMeta,
        argValues: [metaWorkspaceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRecycleBinPurgeAllRecycleBinEntriesConstMeta =>
      const TaskConstMeta(
        debugName: "purge_all_recycle_bin_entries",
        argNames: ["metaWorkspaceId"],
      );

  @override
  Future<void> crateApiRecycleBinPurgeRecycleBinEntry({
    required String identifier,
    String? metaWorkspaceId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(identifier);
          var arg1 = cst_encode_opt_String(metaWorkspaceId);
          return wire.wire__crate__api__recycle_bin__purge_recycle_bin_entry(
            port_,
            arg0,
            arg1,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiRecycleBinPurgeRecycleBinEntryConstMeta,
        argValues: [identifier, metaWorkspaceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRecycleBinPurgeRecycleBinEntryConstMeta =>
      const TaskConstMeta(
        debugName: "purge_recycle_bin_entry",
        argNames: ["identifier", "metaWorkspaceId"],
      );

  @override
  Future<void> crateApiBookmarksTransferBookmark({
    required String recordIdentifier,
    required String previousWorkspaceIdentifier,
    required String targetWorkspaceIdentifier,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(recordIdentifier);
          var arg1 = cst_encode_String(previousWorkspaceIdentifier);
          var arg2 = cst_encode_String(targetWorkspaceIdentifier);
          return wire.wire__crate__api__bookmarks__transfer_bookmark(
            port_,
            arg0,
            arg1,
            arg2,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiBookmarksTransferBookmarkConstMeta,
        argValues: [
          recordIdentifier,
          previousWorkspaceIdentifier,
          targetWorkspaceIdentifier,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBookmarksTransferBookmarkConstMeta =>
      const TaskConstMeta(
        debugName: "transfer_bookmark",
        argNames: [
          "recordIdentifier",
          "previousWorkspaceIdentifier",
          "targetWorkspaceIdentifier",
        ],
      );

  @override
  Future<void> crateApiNotesTransferNote({
    required String recordIdentifier,
    required String previousWorkspaceIdentifier,
    required String targetWorkspaceIdentifier,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(recordIdentifier);
          var arg1 = cst_encode_String(previousWorkspaceIdentifier);
          var arg2 = cst_encode_String(targetWorkspaceIdentifier);
          return wire.wire__crate__api__notes__transfer_note(
            port_,
            arg0,
            arg1,
            arg2,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiNotesTransferNoteConstMeta,
        argValues: [
          recordIdentifier,
          previousWorkspaceIdentifier,
          targetWorkspaceIdentifier,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNotesTransferNoteConstMeta => const TaskConstMeta(
    debugName: "transfer_note",
    argNames: [
      "recordIdentifier",
      "previousWorkspaceIdentifier",
      "targetWorkspaceIdentifier",
    ],
  );

  @override
  Future<void> crateApiRemindersTransferReminder({
    required String recordIdentifier,
    required String previousWorkspaceIdentifier,
    required String targetWorkspaceIdentifier,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(recordIdentifier);
          var arg1 = cst_encode_String(previousWorkspaceIdentifier);
          var arg2 = cst_encode_String(targetWorkspaceIdentifier);
          return wire.wire__crate__api__reminders__transfer_reminder(
            port_,
            arg0,
            arg1,
            arg2,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiRemindersTransferReminderConstMeta,
        argValues: [
          recordIdentifier,
          previousWorkspaceIdentifier,
          targetWorkspaceIdentifier,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRemindersTransferReminderConstMeta =>
      const TaskConstMeta(
        debugName: "transfer_reminder",
        argNames: [
          "recordIdentifier",
          "previousWorkspaceIdentifier",
          "targetWorkspaceIdentifier",
        ],
      );

  @override
  Future<void> crateApiSnippetsTransferSnippet({
    required String recordIdentifier,
    required String previousWorkspaceIdentifier,
    required String targetWorkspaceIdentifier,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(recordIdentifier);
          var arg1 = cst_encode_String(previousWorkspaceIdentifier);
          var arg2 = cst_encode_String(targetWorkspaceIdentifier);
          return wire.wire__crate__api__snippets__transfer_snippet(
            port_,
            arg0,
            arg1,
            arg2,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiSnippetsTransferSnippetConstMeta,
        argValues: [
          recordIdentifier,
          previousWorkspaceIdentifier,
          targetWorkspaceIdentifier,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSnippetsTransferSnippetConstMeta =>
      const TaskConstMeta(
        debugName: "transfer_snippet",
        argNames: [
          "recordIdentifier",
          "previousWorkspaceIdentifier",
          "targetWorkspaceIdentifier",
        ],
      );

  @override
  Future<void> crateApiTodoTransferTodo({
    required String recordIdentifier,
    required String previousWorkspaceIdentifier,
    required String targetWorkspaceIdentifier,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(recordIdentifier);
          var arg1 = cst_encode_String(previousWorkspaceIdentifier);
          var arg2 = cst_encode_String(targetWorkspaceIdentifier);
          return wire.wire__crate__api__todo__transfer_todo(
            port_,
            arg0,
            arg1,
            arg2,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiTodoTransferTodoConstMeta,
        argValues: [
          recordIdentifier,
          previousWorkspaceIdentifier,
          targetWorkspaceIdentifier,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTodoTransferTodoConstMeta => const TaskConstMeta(
    debugName: "transfer_todo",
    argNames: [
      "recordIdentifier",
      "previousWorkspaceIdentifier",
      "targetWorkspaceIdentifier",
    ],
  );

  @override
  Future<void> crateApiUserPreferenceTransferUserPreference({
    required String recordIdentifier,
    required String previousWorkspaceIdentifier,
    required String targetWorkspaceIdentifier,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(recordIdentifier);
          var arg1 = cst_encode_String(previousWorkspaceIdentifier);
          var arg2 = cst_encode_String(targetWorkspaceIdentifier);
          return wire
              .wire__crate__api__user_preference__transfer_user_preference(
                port_,
                arg0,
                arg1,
                arg2,
              );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiUserPreferenceTransferUserPreferenceConstMeta,
        argValues: [
          recordIdentifier,
          previousWorkspaceIdentifier,
          targetWorkspaceIdentifier,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUserPreferenceTransferUserPreferenceConstMeta =>
      const TaskConstMeta(
        debugName: "transfer_user_preference",
        argNames: [
          "recordIdentifier",
          "previousWorkspaceIdentifier",
          "targetWorkspaceIdentifier",
        ],
      );

  @override
  Future<String> crateApiBookmarksUpdateBookmark({
    required String identifier,
    String? title,
    String? url,
    String? tag,
    String? metaWorkspaceId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(identifier);
          var arg1 = cst_encode_opt_String(title);
          var arg2 = cst_encode_opt_String(url);
          var arg3 = cst_encode_opt_String(tag);
          var arg4 = cst_encode_opt_String(metaWorkspaceId);
          return wire.wire__crate__api__bookmarks__update_bookmark(
            port_,
            arg0,
            arg1,
            arg2,
            arg3,
            arg4,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiBookmarksUpdateBookmarkConstMeta,
        argValues: [identifier, title, url, tag, metaWorkspaceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBookmarksUpdateBookmarkConstMeta =>
      const TaskConstMeta(
        debugName: "update_bookmark",
        argNames: ["identifier", "title", "url", "tag", "metaWorkspaceId"],
      );

  @override
  Future<String> crateApiNotesUpdateNote({
    required String identifier,
    String? title,
    String? content,
    List<String>? categories,
    String? metaWorkspaceId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(identifier);
          var arg1 = cst_encode_opt_String(title);
          var arg2 = cst_encode_opt_String(content);
          var arg3 = cst_encode_opt_list_String(categories);
          var arg4 = cst_encode_opt_String(metaWorkspaceId);
          return wire.wire__crate__api__notes__update_note(
            port_,
            arg0,
            arg1,
            arg2,
            arg3,
            arg4,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiNotesUpdateNoteConstMeta,
        argValues: [identifier, title, content, categories, metaWorkspaceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNotesUpdateNoteConstMeta => const TaskConstMeta(
    debugName: "update_note",
    argNames: [
      "identifier",
      "title",
      "content",
      "categories",
      "metaWorkspaceId",
    ],
  );

  @override
  Future<String> crateApiRemindersUpdateReminder({
    required String identifier,
    String? title,
    String? description,
    String? remindAt,
    bool? recurring,
    String? recurrenceRule,
    String? alarmSound,
    String? metaWorkspaceId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(identifier);
          var arg1 = cst_encode_opt_String(title);
          var arg2 = cst_encode_opt_String(description);
          var arg3 = cst_encode_opt_String(remindAt);
          var arg4 = cst_encode_opt_box_autoadd_bool(recurring);
          var arg5 = cst_encode_opt_String(recurrenceRule);
          var arg6 = cst_encode_opt_String(alarmSound);
          var arg7 = cst_encode_opt_String(metaWorkspaceId);
          return wire.wire__crate__api__reminders__update_reminder(
            port_,
            arg0,
            arg1,
            arg2,
            arg3,
            arg4,
            arg5,
            arg6,
            arg7,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiRemindersUpdateReminderConstMeta,
        argValues: [
          identifier,
          title,
          description,
          remindAt,
          recurring,
          recurrenceRule,
          alarmSound,
          metaWorkspaceId,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRemindersUpdateReminderConstMeta =>
      const TaskConstMeta(
        debugName: "update_reminder",
        argNames: [
          "identifier",
          "title",
          "description",
          "remindAt",
          "recurring",
          "recurrenceRule",
          "alarmSound",
          "metaWorkspaceId",
        ],
      );

  @override
  Future<String> crateApiSnippetsUpdateSnippet({
    required String identifier,
    String? title,
    String? language,
    String? code,
    String? description,
    bool? isPinned,
    String? metaWorkspaceId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(identifier);
          var arg1 = cst_encode_opt_String(title);
          var arg2 = cst_encode_opt_String(language);
          var arg3 = cst_encode_opt_String(code);
          var arg4 = cst_encode_opt_String(description);
          var arg5 = cst_encode_opt_box_autoadd_bool(isPinned);
          var arg6 = cst_encode_opt_String(metaWorkspaceId);
          return wire.wire__crate__api__snippets__update_snippet(
            port_,
            arg0,
            arg1,
            arg2,
            arg3,
            arg4,
            arg5,
            arg6,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiSnippetsUpdateSnippetConstMeta,
        argValues: [
          identifier,
          title,
          language,
          code,
          description,
          isPinned,
          metaWorkspaceId,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSnippetsUpdateSnippetConstMeta =>
      const TaskConstMeta(
        debugName: "update_snippet",
        argNames: [
          "identifier",
          "title",
          "language",
          "code",
          "description",
          "isPinned",
          "metaWorkspaceId",
        ],
      );

  @override
  Future<String> crateApiTodoUpdateTodo({
    required String identifier,
    String? title,
    String? description,
    String? priority,
    String? dueDate,
    String? metaWorkspaceId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(identifier);
          var arg1 = cst_encode_opt_String(title);
          var arg2 = cst_encode_opt_String(description);
          var arg3 = cst_encode_opt_String(priority);
          var arg4 = cst_encode_opt_String(dueDate);
          var arg5 = cst_encode_opt_String(metaWorkspaceId);
          return wire.wire__crate__api__todo__update_todo(
            port_,
            arg0,
            arg1,
            arg2,
            arg3,
            arg4,
            arg5,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiTodoUpdateTodoConstMeta,
        argValues: [
          identifier,
          title,
          description,
          priority,
          dueDate,
          metaWorkspaceId,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTodoUpdateTodoConstMeta => const TaskConstMeta(
    debugName: "update_todo",
    argNames: [
      "identifier",
      "title",
      "description",
      "priority",
      "dueDate",
      "metaWorkspaceId",
    ],
  );

  @override
  Future<String> crateApiTodoUpdateTodoDueDate({
    required String identifier,
    String? dueDate,
    String? metaWorkspaceId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(identifier);
          var arg1 = cst_encode_opt_String(dueDate);
          var arg2 = cst_encode_opt_String(metaWorkspaceId);
          return wire.wire__crate__api__todo__update_todo_due_date(
            port_,
            arg0,
            arg1,
            arg2,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiTodoUpdateTodoDueDateConstMeta,
        argValues: [identifier, dueDate, metaWorkspaceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTodoUpdateTodoDueDateConstMeta =>
      const TaskConstMeta(
        debugName: "update_todo_due_date",
        argNames: ["identifier", "dueDate", "metaWorkspaceId"],
      );

  @override
  Future<String> crateApiUserPreferenceUpdateUserPreference({
    required String identifier,
    String? firstName,
    String? lastName,
    String? email,
    String? metaWorkspaceId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(identifier);
          var arg1 = cst_encode_opt_String(firstName);
          var arg2 = cst_encode_opt_String(lastName);
          var arg3 = cst_encode_opt_String(email);
          var arg4 = cst_encode_opt_String(metaWorkspaceId);
          return wire.wire__crate__api__user_preference__update_user_preference(
            port_,
            arg0,
            arg1,
            arg2,
            arg3,
            arg4,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiUserPreferenceUpdateUserPreferenceConstMeta,
        argValues: [identifier, firstName, lastName, email, metaWorkspaceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUserPreferenceUpdateUserPreferenceConstMeta =>
      const TaskConstMeta(
        debugName: "update_user_preference",
        argNames: [
          "identifier",
          "firstName",
          "lastName",
          "email",
          "metaWorkspaceId",
        ],
      );

  @override
  Future<String> crateApiWorkspacesUpdateWorkspace({
    required String identifier,
    String? name,
    String? description,
    bool? isDefault,
    bool? isHidden,
    bool? isSecured,
    String? password,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(identifier);
          var arg1 = cst_encode_opt_String(name);
          var arg2 = cst_encode_opt_String(description);
          var arg3 = cst_encode_opt_box_autoadd_bool(isDefault);
          var arg4 = cst_encode_opt_box_autoadd_bool(isHidden);
          var arg5 = cst_encode_opt_box_autoadd_bool(isSecured);
          var arg6 = cst_encode_opt_String(password);
          return wire.wire__crate__api__workspaces__update_workspace(
            port_,
            arg0,
            arg1,
            arg2,
            arg3,
            arg4,
            arg5,
            arg6,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiWorkspacesUpdateWorkspaceConstMeta,
        argValues: [
          identifier,
          name,
          description,
          isDefault,
          isHidden,
          isSecured,
          password,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWorkspacesUpdateWorkspaceConstMeta =>
      const TaskConstMeta(
        debugName: "update_workspace",
        argNames: [
          "identifier",
          "name",
          "description",
          "isDefault",
          "isHidden",
          "isSecured",
          "password",
        ],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_bool(raw);
  }

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_String(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_bool(deserializer));
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_bool(deserializer));
    } else {
      return null;
    }
  }

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  bool cst_encode_bool(bool raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  int cst_encode_u_8(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  void cst_encode_unit(void raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_bool(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_String(
    List<String>? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_String(self, serializer);
    }
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
