// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/bookmarks.dart';
import 'api/notes.dart';
import 'api/recycle_bin.dart';
import 'api/reminders.dart';
import 'api/simple.dart';
import 'api/snippets.dart';
import 'api/todo.dart';
import 'api/user_preference.dart';
import 'api/workspaces.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_BookmarkTagPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBookmarkTagPtr;

  @protected
  BookmarkTag
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBookmarkTag(
    dynamic raw,
  );

  @protected
  BookmarkTag
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBookmarkTag(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  BookmarkTag
  dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBookmarkTag(
    dynamic raw,
  );

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  BookmarkTag?
  dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBookmarkTag(
    dynamic raw,
  );

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  BookmarkTag
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBookmarkTag(
    SseDeserializer deserializer,
  );

  @protected
  BookmarkTag
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBookmarkTag(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  BookmarkTag
  sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBookmarkTag(
    SseDeserializer deserializer,
  );

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  BookmarkTag?
  sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBookmarkTag(
    SseDeserializer deserializer,
  );

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_String(String raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_list_prim_u_8_strict(utf8.encoder.convert(raw));
  }

  @protected
  ffi.Pointer<ffi.UintPtr>
  cst_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBookmarkTag(
    BookmarkTag raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return wire
        .cst_new_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBookmarkTag(
          cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBookmarkTag(
            raw,
          ),
        );
  }

  @protected
  ffi.Pointer<ffi.Bool> cst_encode_box_autoadd_bool(bool raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return wire.cst_new_box_autoadd_bool(cst_encode_bool(raw));
  }

  @protected
  ffi.Pointer<wire_cst_list_String> cst_encode_list_String(List<String> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_String(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      ans.ref.ptr[i] = cst_encode_String(raw[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_list_prim_u_8_strict(
    Uint8List raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_prim_u_8_strict(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_opt_String(
    String? raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_String(raw);
  }

  @protected
  ffi.Pointer<ffi.UintPtr>
  cst_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBookmarkTag(
    BookmarkTag? raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null
        ? ffi.nullptr
        : cst_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBookmarkTag(
            raw,
          );
  }

  @protected
  ffi.Pointer<ffi.Bool> cst_encode_opt_box_autoadd_bool(bool? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_box_autoadd_bool(raw);
  }

  @protected
  ffi.Pointer<wire_cst_list_String> cst_encode_opt_list_String(
    List<String>? raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_list_String(raw);
  }

  @protected
  int cst_encode_usize(BigInt raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.toSigned(64).toInt();
  }

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBookmarkTag(
    BookmarkTag raw,
  );

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBookmarkTag(
    BookmarkTag raw,
  );

  @protected
  bool cst_encode_bool(bool raw);

  @protected
  int cst_encode_u_8(int raw);

  @protected
  void cst_encode_unit(void raw);

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBookmarkTag(
    BookmarkTag self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBookmarkTag(
    BookmarkTag self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void
  sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBookmarkTag(
    BookmarkTag self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void
  sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBookmarkTag(
    BookmarkTag? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_String(List<String>? self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

// ignore_for_file: camel_case_types, non_constant_identifier_names, avoid_positional_boolean_parameters, annotate_overrides, constant_identifier_names
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import

/// generated by flutter_rust_bridge
class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  RustLibWire.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  void store_dart_post_cobject(DartPostCObjectFnType ptr) {
    return _store_dart_post_cobject(ptr);
  }

  late final _store_dart_post_cobjectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(DartPostCObjectFnType)>>(
        'store_dart_post_cobject',
      );
  late final _store_dart_post_cobject = _store_dart_post_cobjectPtr
      .asFunction<void Function(DartPostCObjectFnType)>();

  void wire__crate__api__todo__change_todo_priority(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> identifier,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> priority,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> meta_workspace_id,
  ) {
    return _wire__crate__api__todo__change_todo_priority(
      port_,
      identifier,
      priority,
      meta_workspace_id,
    );
  }

  late final _wire__crate__api__todo__change_todo_priorityPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_shurbs_wire__crate__api__todo__change_todo_priority');
  late final _wire__crate__api__todo__change_todo_priority =
      _wire__crate__api__todo__change_todo_priorityPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__bookmarks__create_bookmark(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> title,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> url,
    int tag,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> workspace_identifier,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> meta_workspace_id,
  ) {
    return _wire__crate__api__bookmarks__create_bookmark(
      port_,
      title,
      url,
      tag,
      workspace_identifier,
      meta_workspace_id,
    );
  }

  late final _wire__crate__api__bookmarks__create_bookmarkPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.UintPtr,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_shurbs_wire__crate__api__bookmarks__create_bookmark');
  late final _wire__crate__api__bookmarks__create_bookmark =
      _wire__crate__api__bookmarks__create_bookmarkPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__notes__create_note(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> title,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> content,
    ffi.Pointer<wire_cst_list_String> categories,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> workspace_identifier,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> meta_workspace_id,
  ) {
    return _wire__crate__api__notes__create_note(
      port_,
      title,
      content,
      categories,
      workspace_identifier,
      meta_workspace_id,
    );
  }

  late final _wire__crate__api__notes__create_notePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_String>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_shurbs_wire__crate__api__notes__create_note');
  late final _wire__crate__api__notes__create_note =
      _wire__crate__api__notes__create_notePtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_String>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__recycle_bin__create_recycle_bin_entry(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> item_id,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> item_type,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> payload,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> meta_workspace_id,
  ) {
    return _wire__crate__api__recycle_bin__create_recycle_bin_entry(
      port_,
      item_id,
      item_type,
      payload,
      meta_workspace_id,
    );
  }

  late final _wire__crate__api__recycle_bin__create_recycle_bin_entryPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >(
        'frbgen_shurbs_wire__crate__api__recycle_bin__create_recycle_bin_entry',
      );
  late final _wire__crate__api__recycle_bin__create_recycle_bin_entry =
      _wire__crate__api__recycle_bin__create_recycle_bin_entryPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__reminders__create_reminder(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> title,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> description,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> remind_at,
    bool recurring,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> recurrence_rule,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> alarm_sound,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> workspace_identifier,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> meta_workspace_id,
  ) {
    return _wire__crate__api__reminders__create_reminder(
      port_,
      title,
      description,
      remind_at,
      recurring,
      recurrence_rule,
      alarm_sound,
      workspace_identifier,
      meta_workspace_id,
    );
  }

  late final _wire__crate__api__reminders__create_reminderPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Bool,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_shurbs_wire__crate__api__reminders__create_reminder');
  late final _wire__crate__api__reminders__create_reminder =
      _wire__crate__api__reminders__create_reminderPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              bool,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__snippets__create_snippet(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> code,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> title,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> language,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> description,
    bool is_pinned,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> workspace_identifier,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> meta_workspace_id,
  ) {
    return _wire__crate__api__snippets__create_snippet(
      port_,
      code,
      title,
      language,
      description,
      is_pinned,
      workspace_identifier,
      meta_workspace_id,
    );
  }

  late final _wire__crate__api__snippets__create_snippetPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Bool,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_shurbs_wire__crate__api__snippets__create_snippet');
  late final _wire__crate__api__snippets__create_snippet =
      _wire__crate__api__snippets__create_snippetPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              bool,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__todo__create_todo(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> title,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> description,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> priority,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> due_date,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> workspace_identifier,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> meta_workspace_id,
  ) {
    return _wire__crate__api__todo__create_todo(
      port_,
      title,
      description,
      priority,
      due_date,
      workspace_identifier,
      meta_workspace_id,
    );
  }

  late final _wire__crate__api__todo__create_todoPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_shurbs_wire__crate__api__todo__create_todo');
  late final _wire__crate__api__todo__create_todo =
      _wire__crate__api__todo__create_todoPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__user_preference__create_user_preference(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> first_name,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> last_name,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> email,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> meta_workspace_id,
  ) {
    return _wire__crate__api__user_preference__create_user_preference(
      port_,
      first_name,
      last_name,
      email,
      meta_workspace_id,
    );
  }

  late final _wire__crate__api__user_preference__create_user_preferencePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >(
        'frbgen_shurbs_wire__crate__api__user_preference__create_user_preference',
      );
  late final _wire__crate__api__user_preference__create_user_preference =
      _wire__crate__api__user_preference__create_user_preferencePtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__workspaces__create_workspace(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> name,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> description,
  ) {
    return _wire__crate__api__workspaces__create_workspace(
      port_,
      name,
      description,
    );
  }

  late final _wire__crate__api__workspaces__create_workspacePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_shurbs_wire__crate__api__workspaces__create_workspace');
  late final _wire__crate__api__workspaces__create_workspace =
      _wire__crate__api__workspaces__create_workspacePtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__bookmarks__delete_bookmark(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> identifier,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> meta_workspace_id,
  ) {
    return _wire__crate__api__bookmarks__delete_bookmark(
      port_,
      identifier,
      meta_workspace_id,
    );
  }

  late final _wire__crate__api__bookmarks__delete_bookmarkPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_shurbs_wire__crate__api__bookmarks__delete_bookmark');
  late final _wire__crate__api__bookmarks__delete_bookmark =
      _wire__crate__api__bookmarks__delete_bookmarkPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__notes__delete_note(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> identifier,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> meta_workspace_id,
  ) {
    return _wire__crate__api__notes__delete_note(
      port_,
      identifier,
      meta_workspace_id,
    );
  }

  late final _wire__crate__api__notes__delete_notePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_shurbs_wire__crate__api__notes__delete_note');
  late final _wire__crate__api__notes__delete_note =
      _wire__crate__api__notes__delete_notePtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__reminders__delete_reminder(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> identifier,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> meta_workspace_id,
  ) {
    return _wire__crate__api__reminders__delete_reminder(
      port_,
      identifier,
      meta_workspace_id,
    );
  }

  late final _wire__crate__api__reminders__delete_reminderPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_shurbs_wire__crate__api__reminders__delete_reminder');
  late final _wire__crate__api__reminders__delete_reminder =
      _wire__crate__api__reminders__delete_reminderPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__snippets__delete_snippet(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> identifier,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> meta_workspace_id,
  ) {
    return _wire__crate__api__snippets__delete_snippet(
      port_,
      identifier,
      meta_workspace_id,
    );
  }

  late final _wire__crate__api__snippets__delete_snippetPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_shurbs_wire__crate__api__snippets__delete_snippet');
  late final _wire__crate__api__snippets__delete_snippet =
      _wire__crate__api__snippets__delete_snippetPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__todo__delete_todo(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> identifier,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> meta_workspace_id,
  ) {
    return _wire__crate__api__todo__delete_todo(
      port_,
      identifier,
      meta_workspace_id,
    );
  }

  late final _wire__crate__api__todo__delete_todoPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_shurbs_wire__crate__api__todo__delete_todo');
  late final _wire__crate__api__todo__delete_todo =
      _wire__crate__api__todo__delete_todoPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__workspaces__delete_workspace(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> identifier,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> meta_workspace_id,
  ) {
    return _wire__crate__api__workspaces__delete_workspace(
      port_,
      identifier,
      meta_workspace_id,
    );
  }

  late final _wire__crate__api__workspaces__delete_workspacePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_shurbs_wire__crate__api__workspaces__delete_workspace');
  late final _wire__crate__api__workspaces__delete_workspace =
      _wire__crate__api__workspaces__delete_workspacePtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__bookmarks__duplicate_bookmark(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> record_identifier,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> previous_workspace_identifier,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> target_workspace_identifier,
  ) {
    return _wire__crate__api__bookmarks__duplicate_bookmark(
      port_,
      record_identifier,
      previous_workspace_identifier,
      target_workspace_identifier,
    );
  }

  late final _wire__crate__api__bookmarks__duplicate_bookmarkPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_shurbs_wire__crate__api__bookmarks__duplicate_bookmark');
  late final _wire__crate__api__bookmarks__duplicate_bookmark =
      _wire__crate__api__bookmarks__duplicate_bookmarkPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__notes__duplicate_note(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> record_identifier,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> previous_workspace_identifier,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> target_workspace_identifier,
  ) {
    return _wire__crate__api__notes__duplicate_note(
      port_,
      record_identifier,
      previous_workspace_identifier,
      target_workspace_identifier,
    );
  }

  late final _wire__crate__api__notes__duplicate_notePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_shurbs_wire__crate__api__notes__duplicate_note');
  late final _wire__crate__api__notes__duplicate_note =
      _wire__crate__api__notes__duplicate_notePtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__reminders__duplicate_reminder(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> record_identifier,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> previous_workspace_identifier,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> target_workspace_identifier,
  ) {
    return _wire__crate__api__reminders__duplicate_reminder(
      port_,
      record_identifier,
      previous_workspace_identifier,
      target_workspace_identifier,
    );
  }

  late final _wire__crate__api__reminders__duplicate_reminderPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_shurbs_wire__crate__api__reminders__duplicate_reminder');
  late final _wire__crate__api__reminders__duplicate_reminder =
      _wire__crate__api__reminders__duplicate_reminderPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__snippets__duplicate_snippet(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> record_identifier,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> previous_workspace_identifier,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> target_workspace_identifier,
  ) {
    return _wire__crate__api__snippets__duplicate_snippet(
      port_,
      record_identifier,
      previous_workspace_identifier,
      target_workspace_identifier,
    );
  }

  late final _wire__crate__api__snippets__duplicate_snippetPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_shurbs_wire__crate__api__snippets__duplicate_snippet');
  late final _wire__crate__api__snippets__duplicate_snippet =
      _wire__crate__api__snippets__duplicate_snippetPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__todo__duplicate_todo(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> record_identifier,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> previous_workspace_identifier,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> target_workspace_identifier,
  ) {
    return _wire__crate__api__todo__duplicate_todo(
      port_,
      record_identifier,
      previous_workspace_identifier,
      target_workspace_identifier,
    );
  }

  late final _wire__crate__api__todo__duplicate_todoPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_shurbs_wire__crate__api__todo__duplicate_todo');
  late final _wire__crate__api__todo__duplicate_todo =
      _wire__crate__api__todo__duplicate_todoPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__user_preference__duplicate_user_preference(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> record_identifier,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> previous_workspace_identifier,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> target_workspace_identifier,
  ) {
    return _wire__crate__api__user_preference__duplicate_user_preference(
      port_,
      record_identifier,
      previous_workspace_identifier,
      target_workspace_identifier,
    );
  }

  late final _wire__crate__api__user_preference__duplicate_user_preferencePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >(
        'frbgen_shurbs_wire__crate__api__user_preference__duplicate_user_preference',
      );
  late final _wire__crate__api__user_preference__duplicate_user_preference =
      _wire__crate__api__user_preference__duplicate_user_preferencePtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__bookmarks__get_all_bookmarks(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> meta_workspace_id,
  ) {
    return _wire__crate__api__bookmarks__get_all_bookmarks(
      port_,
      meta_workspace_id,
    );
  }

  late final _wire__crate__api__bookmarks__get_all_bookmarksPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_shurbs_wire__crate__api__bookmarks__get_all_bookmarks');
  late final _wire__crate__api__bookmarks__get_all_bookmarks =
      _wire__crate__api__bookmarks__get_all_bookmarksPtr
          .asFunction<
            void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
          >();

  void wire__crate__api__notes__get_all_notes(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> meta_workspace_id,
  ) {
    return _wire__crate__api__notes__get_all_notes(port_, meta_workspace_id);
  }

  late final _wire__crate__api__notes__get_all_notesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_shurbs_wire__crate__api__notes__get_all_notes');
  late final _wire__crate__api__notes__get_all_notes =
      _wire__crate__api__notes__get_all_notesPtr
          .asFunction<
            void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
          >();

  void wire__crate__api__recycle_bin__get_all_recycle_bin_entries(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> meta_workspace_id,
  ) {
    return _wire__crate__api__recycle_bin__get_all_recycle_bin_entries(
      port_,
      meta_workspace_id,
    );
  }

  late final _wire__crate__api__recycle_bin__get_all_recycle_bin_entriesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >(
        'frbgen_shurbs_wire__crate__api__recycle_bin__get_all_recycle_bin_entries',
      );
  late final _wire__crate__api__recycle_bin__get_all_recycle_bin_entries =
      _wire__crate__api__recycle_bin__get_all_recycle_bin_entriesPtr
          .asFunction<
            void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
          >();

  void wire__crate__api__reminders__get_all_reminders(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> meta_workspace_id,
  ) {
    return _wire__crate__api__reminders__get_all_reminders(
      port_,
      meta_workspace_id,
    );
  }

  late final _wire__crate__api__reminders__get_all_remindersPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_shurbs_wire__crate__api__reminders__get_all_reminders');
  late final _wire__crate__api__reminders__get_all_reminders =
      _wire__crate__api__reminders__get_all_remindersPtr
          .asFunction<
            void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
          >();

  void wire__crate__api__snippets__get_all_snippets(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> meta_workspace_id,
  ) {
    return _wire__crate__api__snippets__get_all_snippets(
      port_,
      meta_workspace_id,
    );
  }

  late final _wire__crate__api__snippets__get_all_snippetsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_shurbs_wire__crate__api__snippets__get_all_snippets');
  late final _wire__crate__api__snippets__get_all_snippets =
      _wire__crate__api__snippets__get_all_snippetsPtr
          .asFunction<
            void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
          >();

  void wire__crate__api__todo__get_all_todos(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> meta_workspace_id,
  ) {
    return _wire__crate__api__todo__get_all_todos(port_, meta_workspace_id);
  }

  late final _wire__crate__api__todo__get_all_todosPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_shurbs_wire__crate__api__todo__get_all_todos');
  late final _wire__crate__api__todo__get_all_todos =
      _wire__crate__api__todo__get_all_todosPtr
          .asFunction<
            void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
          >();

  void wire__crate__api__bookmarks__get_bookmark(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> identifier,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> meta_workspace_id,
  ) {
    return _wire__crate__api__bookmarks__get_bookmark(
      port_,
      identifier,
      meta_workspace_id,
    );
  }

  late final _wire__crate__api__bookmarks__get_bookmarkPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_shurbs_wire__crate__api__bookmarks__get_bookmark');
  late final _wire__crate__api__bookmarks__get_bookmark =
      _wire__crate__api__bookmarks__get_bookmarkPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__bookmarks__get_bookmarks_by_tag(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> tag,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> meta_workspace_id,
  ) {
    return _wire__crate__api__bookmarks__get_bookmarks_by_tag(
      port_,
      tag,
      meta_workspace_id,
    );
  }

  late final _wire__crate__api__bookmarks__get_bookmarks_by_tagPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_shurbs_wire__crate__api__bookmarks__get_bookmarks_by_tag');
  late final _wire__crate__api__bookmarks__get_bookmarks_by_tag =
      _wire__crate__api__bookmarks__get_bookmarks_by_tagPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__notes__get_note(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> identifier,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> meta_workspace_id,
  ) {
    return _wire__crate__api__notes__get_note(
      port_,
      identifier,
      meta_workspace_id,
    );
  }

  late final _wire__crate__api__notes__get_notePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_shurbs_wire__crate__api__notes__get_note');
  late final _wire__crate__api__notes__get_note =
      _wire__crate__api__notes__get_notePtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__bookmarks__get_recently_added_bookmarks(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> meta_workspace_id,
  ) {
    return _wire__crate__api__bookmarks__get_recently_added_bookmarks(
      port_,
      meta_workspace_id,
    );
  }

  late final _wire__crate__api__bookmarks__get_recently_added_bookmarksPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >(
        'frbgen_shurbs_wire__crate__api__bookmarks__get_recently_added_bookmarks',
      );
  late final _wire__crate__api__bookmarks__get_recently_added_bookmarks =
      _wire__crate__api__bookmarks__get_recently_added_bookmarksPtr
          .asFunction<
            void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
          >();

  void wire__crate__api__notes__get_recently_added_notes(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> meta_workspace_id,
  ) {
    return _wire__crate__api__notes__get_recently_added_notes(
      port_,
      meta_workspace_id,
    );
  }

  late final _wire__crate__api__notes__get_recently_added_notesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_shurbs_wire__crate__api__notes__get_recently_added_notes');
  late final _wire__crate__api__notes__get_recently_added_notes =
      _wire__crate__api__notes__get_recently_added_notesPtr
          .asFunction<
            void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
          >();

  void wire__crate__api__snippets__get_recently_added_snippets(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> meta_workspace_id,
  ) {
    return _wire__crate__api__snippets__get_recently_added_snippets(
      port_,
      meta_workspace_id,
    );
  }

  late final _wire__crate__api__snippets__get_recently_added_snippetsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >(
        'frbgen_shurbs_wire__crate__api__snippets__get_recently_added_snippets',
      );
  late final _wire__crate__api__snippets__get_recently_added_snippets =
      _wire__crate__api__snippets__get_recently_added_snippetsPtr
          .asFunction<
            void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
          >();

  void wire__crate__api__recycle_bin__get_recycle_bin_entries_by_type(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> item_type,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> meta_workspace_id,
  ) {
    return _wire__crate__api__recycle_bin__get_recycle_bin_entries_by_type(
      port_,
      item_type,
      meta_workspace_id,
    );
  }

  late final _wire__crate__api__recycle_bin__get_recycle_bin_entries_by_typePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >(
        'frbgen_shurbs_wire__crate__api__recycle_bin__get_recycle_bin_entries_by_type',
      );
  late final _wire__crate__api__recycle_bin__get_recycle_bin_entries_by_type =
      _wire__crate__api__recycle_bin__get_recycle_bin_entries_by_typePtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__recycle_bin__get_recycle_bin_entry(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> identifier,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> meta_workspace_id,
  ) {
    return _wire__crate__api__recycle_bin__get_recycle_bin_entry(
      port_,
      identifier,
      meta_workspace_id,
    );
  }

  late final _wire__crate__api__recycle_bin__get_recycle_bin_entryPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_shurbs_wire__crate__api__recycle_bin__get_recycle_bin_entry');
  late final _wire__crate__api__recycle_bin__get_recycle_bin_entry =
      _wire__crate__api__recycle_bin__get_recycle_bin_entryPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__reminders__get_reminder(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> identifier,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> meta_workspace_id,
  ) {
    return _wire__crate__api__reminders__get_reminder(
      port_,
      identifier,
      meta_workspace_id,
    );
  }

  late final _wire__crate__api__reminders__get_reminderPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_shurbs_wire__crate__api__reminders__get_reminder');
  late final _wire__crate__api__reminders__get_reminder =
      _wire__crate__api__reminders__get_reminderPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__snippets__get_snippet(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> identifier,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> meta_workspace_id,
  ) {
    return _wire__crate__api__snippets__get_snippet(
      port_,
      identifier,
      meta_workspace_id,
    );
  }

  late final _wire__crate__api__snippets__get_snippetPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_shurbs_wire__crate__api__snippets__get_snippet');
  late final _wire__crate__api__snippets__get_snippet =
      _wire__crate__api__snippets__get_snippetPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__todo__get_todo(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> identifier,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> meta_workspace_id,
  ) {
    return _wire__crate__api__todo__get_todo(
      port_,
      identifier,
      meta_workspace_id,
    );
  }

  late final _wire__crate__api__todo__get_todoPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_shurbs_wire__crate__api__todo__get_todo');
  late final _wire__crate__api__todo__get_todo =
      _wire__crate__api__todo__get_todoPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__user_preference__get_user_preference(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> meta_workspace_id,
  ) {
    return _wire__crate__api__user_preference__get_user_preference(
      port_,
      meta_workspace_id,
    );
  }

  late final _wire__crate__api__user_preference__get_user_preferencePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_shurbs_wire__crate__api__user_preference__get_user_preference');
  late final _wire__crate__api__user_preference__get_user_preference =
      _wire__crate__api__user_preference__get_user_preferencePtr
          .asFunction<
            void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
          >();

  void wire__crate__api__workspaces__get_workspace_by_id(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> id,
  ) {
    return _wire__crate__api__workspaces__get_workspace_by_id(port_, id);
  }

  late final _wire__crate__api__workspaces__get_workspace_by_idPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_shurbs_wire__crate__api__workspaces__get_workspace_by_id');
  late final _wire__crate__api__workspaces__get_workspace_by_id =
      _wire__crate__api__workspaces__get_workspace_by_idPtr
          .asFunction<
            void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
          >();

  WireSyncRust2DartDco wire__crate__api__simple__greet(
    ffi.Pointer<wire_cst_list_prim_u_8_strict> name,
  ) {
    return _wire__crate__api__simple__greet(name);
  }

  late final _wire__crate__api__simple__greetPtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_shurbs_wire__crate__api__simple__greet');
  late final _wire__crate__api__simple__greet =
      _wire__crate__api__simple__greetPtr
          .asFunction<
            WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__simple__init_app(int port_) {
    return _wire__crate__api__simple__init_app(port_);
  }

  late final _wire__crate__api__simple__init_appPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
        'frbgen_shurbs_wire__crate__api__simple__init_app',
      );
  late final _wire__crate__api__simple__init_app =
      _wire__crate__api__simple__init_appPtr.asFunction<void Function(int)>();

  void wire__crate__api__simple__init_kernel(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> database_url,
  ) {
    return _wire__crate__api__simple__init_kernel(port_, database_url);
  }

  late final _wire__crate__api__simple__init_kernelPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_shurbs_wire__crate__api__simple__init_kernel');
  late final _wire__crate__api__simple__init_kernel =
      _wire__crate__api__simple__init_kernelPtr
          .asFunction<
            void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
          >();

  void wire__crate__api__workspaces__list_workspaces(int port_) {
    return _wire__crate__api__workspaces__list_workspaces(port_);
  }

  late final _wire__crate__api__workspaces__list_workspacesPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
        'frbgen_shurbs_wire__crate__api__workspaces__list_workspaces',
      );
  late final _wire__crate__api__workspaces__list_workspaces =
      _wire__crate__api__workspaces__list_workspacesPtr
          .asFunction<void Function(int)>();

  void wire__crate__api__todo__mark_todo_done(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> identifier,
    bool done,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> meta_workspace_id,
  ) {
    return _wire__crate__api__todo__mark_todo_done(
      port_,
      identifier,
      done,
      meta_workspace_id,
    );
  }

  late final _wire__crate__api__todo__mark_todo_donePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Bool,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_shurbs_wire__crate__api__todo__mark_todo_done');
  late final _wire__crate__api__todo__mark_todo_done =
      _wire__crate__api__todo__mark_todo_donePtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              bool,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__recycle_bin__purge_all_recycle_bin_entries(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> meta_workspace_id,
  ) {
    return _wire__crate__api__recycle_bin__purge_all_recycle_bin_entries(
      port_,
      meta_workspace_id,
    );
  }

  late final _wire__crate__api__recycle_bin__purge_all_recycle_bin_entriesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >(
        'frbgen_shurbs_wire__crate__api__recycle_bin__purge_all_recycle_bin_entries',
      );
  late final _wire__crate__api__recycle_bin__purge_all_recycle_bin_entries =
      _wire__crate__api__recycle_bin__purge_all_recycle_bin_entriesPtr
          .asFunction<
            void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
          >();

  void wire__crate__api__recycle_bin__purge_recycle_bin_entry(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> identifier,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> meta_workspace_id,
  ) {
    return _wire__crate__api__recycle_bin__purge_recycle_bin_entry(
      port_,
      identifier,
      meta_workspace_id,
    );
  }

  late final _wire__crate__api__recycle_bin__purge_recycle_bin_entryPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_shurbs_wire__crate__api__recycle_bin__purge_recycle_bin_entry');
  late final _wire__crate__api__recycle_bin__purge_recycle_bin_entry =
      _wire__crate__api__recycle_bin__purge_recycle_bin_entryPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__bookmarks__transfer_bookmark(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> record_identifier,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> previous_workspace_identifier,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> target_workspace_identifier,
  ) {
    return _wire__crate__api__bookmarks__transfer_bookmark(
      port_,
      record_identifier,
      previous_workspace_identifier,
      target_workspace_identifier,
    );
  }

  late final _wire__crate__api__bookmarks__transfer_bookmarkPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_shurbs_wire__crate__api__bookmarks__transfer_bookmark');
  late final _wire__crate__api__bookmarks__transfer_bookmark =
      _wire__crate__api__bookmarks__transfer_bookmarkPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__notes__transfer_note(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> record_identifier,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> previous_workspace_identifier,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> target_workspace_identifier,
  ) {
    return _wire__crate__api__notes__transfer_note(
      port_,
      record_identifier,
      previous_workspace_identifier,
      target_workspace_identifier,
    );
  }

  late final _wire__crate__api__notes__transfer_notePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_shurbs_wire__crate__api__notes__transfer_note');
  late final _wire__crate__api__notes__transfer_note =
      _wire__crate__api__notes__transfer_notePtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__reminders__transfer_reminder(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> record_identifier,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> previous_workspace_identifier,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> target_workspace_identifier,
  ) {
    return _wire__crate__api__reminders__transfer_reminder(
      port_,
      record_identifier,
      previous_workspace_identifier,
      target_workspace_identifier,
    );
  }

  late final _wire__crate__api__reminders__transfer_reminderPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_shurbs_wire__crate__api__reminders__transfer_reminder');
  late final _wire__crate__api__reminders__transfer_reminder =
      _wire__crate__api__reminders__transfer_reminderPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__snippets__transfer_snippet(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> record_identifier,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> previous_workspace_identifier,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> target_workspace_identifier,
  ) {
    return _wire__crate__api__snippets__transfer_snippet(
      port_,
      record_identifier,
      previous_workspace_identifier,
      target_workspace_identifier,
    );
  }

  late final _wire__crate__api__snippets__transfer_snippetPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_shurbs_wire__crate__api__snippets__transfer_snippet');
  late final _wire__crate__api__snippets__transfer_snippet =
      _wire__crate__api__snippets__transfer_snippetPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__todo__transfer_todo(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> record_identifier,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> previous_workspace_identifier,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> target_workspace_identifier,
  ) {
    return _wire__crate__api__todo__transfer_todo(
      port_,
      record_identifier,
      previous_workspace_identifier,
      target_workspace_identifier,
    );
  }

  late final _wire__crate__api__todo__transfer_todoPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_shurbs_wire__crate__api__todo__transfer_todo');
  late final _wire__crate__api__todo__transfer_todo =
      _wire__crate__api__todo__transfer_todoPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__user_preference__transfer_user_preference(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> record_identifier,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> previous_workspace_identifier,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> target_workspace_identifier,
  ) {
    return _wire__crate__api__user_preference__transfer_user_preference(
      port_,
      record_identifier,
      previous_workspace_identifier,
      target_workspace_identifier,
    );
  }

  late final _wire__crate__api__user_preference__transfer_user_preferencePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >(
        'frbgen_shurbs_wire__crate__api__user_preference__transfer_user_preference',
      );
  late final _wire__crate__api__user_preference__transfer_user_preference =
      _wire__crate__api__user_preference__transfer_user_preferencePtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__bookmarks__update_bookmark(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> identifier,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> title,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> url,
    ffi.Pointer<ffi.UintPtr> tag,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> meta_workspace_id,
  ) {
    return _wire__crate__api__bookmarks__update_bookmark(
      port_,
      identifier,
      title,
      url,
      tag,
      meta_workspace_id,
    );
  }

  late final _wire__crate__api__bookmarks__update_bookmarkPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<ffi.UintPtr>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_shurbs_wire__crate__api__bookmarks__update_bookmark');
  late final _wire__crate__api__bookmarks__update_bookmark =
      _wire__crate__api__bookmarks__update_bookmarkPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<ffi.UintPtr>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__notes__update_note(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> identifier,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> title,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> content,
    ffi.Pointer<wire_cst_list_String> categories,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> meta_workspace_id,
  ) {
    return _wire__crate__api__notes__update_note(
      port_,
      identifier,
      title,
      content,
      categories,
      meta_workspace_id,
    );
  }

  late final _wire__crate__api__notes__update_notePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_String>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_shurbs_wire__crate__api__notes__update_note');
  late final _wire__crate__api__notes__update_note =
      _wire__crate__api__notes__update_notePtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_String>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__reminders__update_reminder(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> identifier,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> title,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> description,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> remind_at,
    ffi.Pointer<ffi.Bool> recurring,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> recurrence_rule,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> alarm_sound,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> meta_workspace_id,
  ) {
    return _wire__crate__api__reminders__update_reminder(
      port_,
      identifier,
      title,
      description,
      remind_at,
      recurring,
      recurrence_rule,
      alarm_sound,
      meta_workspace_id,
    );
  }

  late final _wire__crate__api__reminders__update_reminderPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<ffi.Bool>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_shurbs_wire__crate__api__reminders__update_reminder');
  late final _wire__crate__api__reminders__update_reminder =
      _wire__crate__api__reminders__update_reminderPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<ffi.Bool>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__snippets__update_snippet(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> identifier,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> title,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> language,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> code,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> description,
    ffi.Pointer<ffi.Bool> is_pinned,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> meta_workspace_id,
  ) {
    return _wire__crate__api__snippets__update_snippet(
      port_,
      identifier,
      title,
      language,
      code,
      description,
      is_pinned,
      meta_workspace_id,
    );
  }

  late final _wire__crate__api__snippets__update_snippetPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<ffi.Bool>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_shurbs_wire__crate__api__snippets__update_snippet');
  late final _wire__crate__api__snippets__update_snippet =
      _wire__crate__api__snippets__update_snippetPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<ffi.Bool>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__todo__update_todo(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> identifier,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> title,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> description,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> priority,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> due_date,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> meta_workspace_id,
  ) {
    return _wire__crate__api__todo__update_todo(
      port_,
      identifier,
      title,
      description,
      priority,
      due_date,
      meta_workspace_id,
    );
  }

  late final _wire__crate__api__todo__update_todoPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_shurbs_wire__crate__api__todo__update_todo');
  late final _wire__crate__api__todo__update_todo =
      _wire__crate__api__todo__update_todoPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__todo__update_todo_due_date(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> identifier,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> due_date,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> meta_workspace_id,
  ) {
    return _wire__crate__api__todo__update_todo_due_date(
      port_,
      identifier,
      due_date,
      meta_workspace_id,
    );
  }

  late final _wire__crate__api__todo__update_todo_due_datePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_shurbs_wire__crate__api__todo__update_todo_due_date');
  late final _wire__crate__api__todo__update_todo_due_date =
      _wire__crate__api__todo__update_todo_due_datePtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__user_preference__update_user_preference(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> identifier,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> first_name,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> last_name,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> email,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> meta_workspace_id,
  ) {
    return _wire__crate__api__user_preference__update_user_preference(
      port_,
      identifier,
      first_name,
      last_name,
      email,
      meta_workspace_id,
    );
  }

  late final _wire__crate__api__user_preference__update_user_preferencePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >(
        'frbgen_shurbs_wire__crate__api__user_preference__update_user_preference',
      );
  late final _wire__crate__api__user_preference__update_user_preference =
      _wire__crate__api__user_preference__update_user_preferencePtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__workspaces__update_workspace(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> identifier,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> name,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> description,
    ffi.Pointer<ffi.Bool> is_default,
    ffi.Pointer<ffi.Bool> is_hidden,
  ) {
    return _wire__crate__api__workspaces__update_workspace(
      port_,
      identifier,
      name,
      description,
      is_default,
      is_hidden,
    );
  }

  late final _wire__crate__api__workspaces__update_workspacePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<ffi.Bool>,
            ffi.Pointer<ffi.Bool>,
          )
        >
      >('frbgen_shurbs_wire__crate__api__workspaces__update_workspace');
  late final _wire__crate__api__workspaces__update_workspace =
      _wire__crate__api__workspaces__update_workspacePtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<ffi.Bool>,
              ffi.Pointer<ffi.Bool>,
            )
          >();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBookmarkTag(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBookmarkTag(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBookmarkTagPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_shurbs_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBookmarkTag',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBookmarkTag =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBookmarkTagPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBookmarkTag(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBookmarkTag(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBookmarkTagPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_shurbs_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBookmarkTag',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBookmarkTag =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBookmarkTagPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  ffi.Pointer<ffi.UintPtr>
  cst_new_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBookmarkTag(
    int value,
  ) {
    return _cst_new_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBookmarkTag(
      value,
    );
  }

  late final _cst_new_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBookmarkTagPtr =
      _lookup<
        ffi.NativeFunction<ffi.Pointer<ffi.UintPtr> Function(ffi.UintPtr)>
      >(
        'frbgen_shurbs_cst_new_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBookmarkTag',
      );
  late final _cst_new_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBookmarkTag =
      _cst_new_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBookmarkTagPtr
          .asFunction<ffi.Pointer<ffi.UintPtr> Function(int)>();

  ffi.Pointer<ffi.Bool> cst_new_box_autoadd_bool(bool value) {
    return _cst_new_box_autoadd_bool(value);
  }

  late final _cst_new_box_autoadd_boolPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Bool> Function(ffi.Bool)>>(
        'frbgen_shurbs_cst_new_box_autoadd_bool',
      );
  late final _cst_new_box_autoadd_bool = _cst_new_box_autoadd_boolPtr
      .asFunction<ffi.Pointer<ffi.Bool> Function(bool)>();

  ffi.Pointer<wire_cst_list_String> cst_new_list_String(int len) {
    return _cst_new_list_String(len);
  }

  late final _cst_new_list_StringPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_String> Function(ffi.Int32)
        >
      >('frbgen_shurbs_cst_new_list_String');
  late final _cst_new_list_String = _cst_new_list_StringPtr
      .asFunction<ffi.Pointer<wire_cst_list_String> Function(int)>();

  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_new_list_prim_u_8_strict(
    int len,
  ) {
    return _cst_new_list_prim_u_8_strict(len);
  }

  late final _cst_new_list_prim_u_8_strictPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_prim_u_8_strict> Function(ffi.Int32)
        >
      >('frbgen_shurbs_cst_new_list_prim_u_8_strict');
  late final _cst_new_list_prim_u_8_strict = _cst_new_list_prim_u_8_strictPtr
      .asFunction<ffi.Pointer<wire_cst_list_prim_u_8_strict> Function(int)>();

  int dummy_method_to_enforce_bundling() {
    return _dummy_method_to_enforce_bundling();
  }

  late final _dummy_method_to_enforce_bundlingPtr =
      _lookup<ffi.NativeFunction<ffi.Int64 Function()>>(
        'dummy_method_to_enforce_bundling',
      );
  late final _dummy_method_to_enforce_bundling =
      _dummy_method_to_enforce_bundlingPtr.asFunction<int Function()>();
}

typedef DartPort = ffi.Int64;
typedef DartDartPort = int;
typedef DartPostCObjectFnTypeFunction =
    ffi.Bool Function(DartPort port_id, ffi.Pointer<ffi.Void> message);
typedef DartDartPostCObjectFnTypeFunction =
    bool Function(DartDartPort port_id, ffi.Pointer<ffi.Void> message);
typedef DartPostCObjectFnType =
    ffi.Pointer<ffi.NativeFunction<DartPostCObjectFnTypeFunction>>;

final class wire_cst_list_prim_u_8_strict extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_list_String extends ffi.Struct {
  external ffi.Pointer<ffi.Pointer<wire_cst_list_prim_u_8_strict>> ptr;

  @ffi.Int32()
  external int len;
}
