//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "users")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub identifier: Uuid,
    pub first_name: Option<String>,
    pub last_name: Option<String>,
    #[sea_orm(unique)]
    pub email: String,
    pub password: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: Option<DateTimeWithTimeZone>,
    pub is_active: bool,
    pub profile_picture: Option<String>,
    #[sea_orm(unique)]
    pub username: Option<String>,
    pub country_identifier: Option<String>,
    pub enable_2fa: bool,
    pub enable_biometrics: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::audio_books::Entity")]
    AudioBooks,
    #[sea_orm(has_many = "super::backup_emails::Entity")]
    BackupEmails,
    #[sea_orm(
        belongs_to = "super::countries::Entity",
        from = "Column::CountryIdentifier",
        to = "super::countries::Column::Identifier",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Countries,
    #[sea_orm(has_many = "super::notifications::Entity")]
    Notifications,
    #[sea_orm(has_many = "super::one_time_passwords::Entity")]
    OneTimePasswords,
    #[sea_orm(has_many = "super::playlists::Entity")]
    Playlists,
}

impl Related<super::audio_books::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AudioBooks.def()
    }
}

impl Related<super::backup_emails::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BackupEmails.def()
    }
}

impl Related<super::countries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Countries.def()
    }
}

impl Related<super::notifications::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Notifications.def()
    }
}

impl Related<super::one_time_passwords::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OneTimePasswords.def()
    }
}

impl Related<super::playlists::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Playlists.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::audio_books::Entity")]
    AudioBooks,
    #[sea_orm(entity = "super::backup_emails::Entity")]
    BackupEmails,
    #[sea_orm(entity = "super::countries::Entity")]
    Countries,
    #[sea_orm(entity = "super::notifications::Entity")]
    Notifications,
    #[sea_orm(entity = "super::one_time_passwords::Entity")]
    OneTimePasswords,
    #[sea_orm(entity = "super::playlists::Entity")]
    Playlists,
}
