// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `parse_tag`

Future<String> createBookmark({
  required String title,
  required String url,
  required BookmarkTag tag,
  String? workspaceIdentifier,
  String? metaWorkspaceId,
}) => RustLib.instance.api.crateApiBookmarksCreateBookmark(
  title: title,
  url: url,
  tag: tag,
  workspaceIdentifier: workspaceIdentifier,
  metaWorkspaceId: metaWorkspaceId,
);

Future<String?> getBookmark({
  required String identifier,
  String? metaWorkspaceId,
}) => RustLib.instance.api.crateApiBookmarksGetBookmark(
  identifier: identifier,
  metaWorkspaceId: metaWorkspaceId,
);

Future<String> getAllBookmarks({String? metaWorkspaceId}) => RustLib
    .instance
    .api
    .crateApiBookmarksGetAllBookmarks(metaWorkspaceId: metaWorkspaceId);

Future<String> getBookmarksByTag({
  required String tag,
  String? metaWorkspaceId,
}) => RustLib.instance.api.crateApiBookmarksGetBookmarksByTag(
  tag: tag,
  metaWorkspaceId: metaWorkspaceId,
);

Future<String> getRecentlyAddedBookmarks({String? metaWorkspaceId}) =>
    RustLib.instance.api.crateApiBookmarksGetRecentlyAddedBookmarks(
      metaWorkspaceId: metaWorkspaceId,
    );

Future<String> updateBookmark({
  required String identifier,
  String? title,
  String? url,
  BookmarkTag? tag,
  String? metaWorkspaceId,
}) => RustLib.instance.api.crateApiBookmarksUpdateBookmark(
  identifier: identifier,
  title: title,
  url: url,
  tag: tag,
  metaWorkspaceId: metaWorkspaceId,
);

Future<void> deleteBookmark({
  required String identifier,
  String? metaWorkspaceId,
}) => RustLib.instance.api.crateApiBookmarksDeleteBookmark(
  identifier: identifier,
  metaWorkspaceId: metaWorkspaceId,
);

Future<void> duplicateBookmark({
  required String recordIdentifier,
  required String previousWorkspaceIdentifier,
  required String targetWorkspaceIdentifier,
}) => RustLib.instance.api.crateApiBookmarksDuplicateBookmark(
  recordIdentifier: recordIdentifier,
  previousWorkspaceIdentifier: previousWorkspaceIdentifier,
  targetWorkspaceIdentifier: targetWorkspaceIdentifier,
);

Future<void> transferBookmark({
  required String recordIdentifier,
  required String previousWorkspaceIdentifier,
  required String targetWorkspaceIdentifier,
}) => RustLib.instance.api.crateApiBookmarksTransferBookmark(
  recordIdentifier: recordIdentifier,
  previousWorkspaceIdentifier: previousWorkspaceIdentifier,
  targetWorkspaceIdentifier: targetWorkspaceIdentifier,
);

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BookmarkTag>>
abstract class BookmarkTag implements RustOpaqueInterface {}
