// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Initialise the kernel (opens the database and runs migrations).
/// Call this once from Flutter before using any other API.
/// `database_url` examples:
///   - SQLite file : `"sqlite:///path/to/shurbs.db?mode=rwc"`
///   - In-memory   : `"sqlite::memory:"`
Future<void> initKernel({required String databaseUrl}) =>
    RustLib.instance.api.crateApiKernelInitKernel(databaseUrl: databaseUrl);
