// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `parse_item_type`

/// `payload` — JSON-serialized copy of the deleted record.
Future<String> createRecycleBinEntry({
  required String itemId,
  required String itemType,
  required String payload,
  String? metaWorkspaceId,
}) => RustLib.instance.api.crateApiRecycleBinCreateRecycleBinEntry(
  itemId: itemId,
  itemType: itemType,
  payload: payload,
  metaWorkspaceId: metaWorkspaceId,
);

Future<String> getAllRecycleBinEntries({String? metaWorkspaceId}) =>
    RustLib.instance.api.crateApiRecycleBinGetAllRecycleBinEntries(
      metaWorkspaceId: metaWorkspaceId,
    );

Future<String?> getRecycleBinEntry({
  required String identifier,
  String? metaWorkspaceId,
}) => RustLib.instance.api.crateApiRecycleBinGetRecycleBinEntry(
  identifier: identifier,
  metaWorkspaceId: metaWorkspaceId,
);

/// `item_type` — one of: `"todo"`, `"note"`, `"reminder"`, `"snippet"`,
/// `"bookmark"`, `"workspace"`.
Future<String> getRecycleBinEntriesByType({
  required String itemType,
  String? metaWorkspaceId,
}) => RustLib.instance.api.crateApiRecycleBinGetRecycleBinEntriesByType(
  itemType: itemType,
  metaWorkspaceId: metaWorkspaceId,
);

Future<void> purgeRecycleBinEntry({
  required String identifier,
  String? metaWorkspaceId,
}) => RustLib.instance.api.crateApiRecycleBinPurgeRecycleBinEntry(
  identifier: identifier,
  metaWorkspaceId: metaWorkspaceId,
);

Future<void> purgeAllRecycleBinEntries({String? metaWorkspaceId}) =>
    RustLib.instance.api.crateApiRecycleBinPurgeAllRecycleBinEntries(
      metaWorkspaceId: metaWorkspaceId,
    );
