// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// `remind_at` — RFC 3339 / ISO 8601 datetime string with timezone,
/// e.g. `"2026-04-10T09:00:00+01:00"`.
Future<String> createReminder({
  required String title,
  String? description,
  required String remindAt,
  required bool recurring,
  String? recurrenceRule,
  String? alarmSound,
  String? workspaceIdentifier,
  String? metaWorkspaceId,
}) => RustLib.instance.api.crateApiRemindersCreateReminder(
  title: title,
  description: description,
  remindAt: remindAt,
  recurring: recurring,
  recurrenceRule: recurrenceRule,
  alarmSound: alarmSound,
  workspaceIdentifier: workspaceIdentifier,
  metaWorkspaceId: metaWorkspaceId,
);

Future<String?> getReminder({
  required String identifier,
  String? metaWorkspaceId,
}) => RustLib.instance.api.crateApiRemindersGetReminder(
  identifier: identifier,
  metaWorkspaceId: metaWorkspaceId,
);

Future<String> getAllReminders({String? metaWorkspaceId}) => RustLib
    .instance
    .api
    .crateApiRemindersGetAllReminders(metaWorkspaceId: metaWorkspaceId);

Future<String> updateReminder({
  required String identifier,
  String? title,
  String? description,
  String? remindAt,
  bool? recurring,
  String? recurrenceRule,
  String? alarmSound,
  String? metaWorkspaceId,
}) => RustLib.instance.api.crateApiRemindersUpdateReminder(
  identifier: identifier,
  title: title,
  description: description,
  remindAt: remindAt,
  recurring: recurring,
  recurrenceRule: recurrenceRule,
  alarmSound: alarmSound,
  metaWorkspaceId: metaWorkspaceId,
);

Future<void> deleteReminder({
  required String identifier,
  String? metaWorkspaceId,
}) => RustLib.instance.api.crateApiRemindersDeleteReminder(
  identifier: identifier,
  metaWorkspaceId: metaWorkspaceId,
);

Future<void> duplicateReminder({
  required String recordIdentifier,
  required String previousWorkspaceIdentifier,
  required String targetWorkspaceIdentifier,
}) => RustLib.instance.api.crateApiRemindersDuplicateReminder(
  recordIdentifier: recordIdentifier,
  previousWorkspaceIdentifier: previousWorkspaceIdentifier,
  targetWorkspaceIdentifier: targetWorkspaceIdentifier,
);

Future<void> transferReminder({
  required String recordIdentifier,
  required String previousWorkspaceIdentifier,
  required String targetWorkspaceIdentifier,
}) => RustLib.instance.api.crateApiRemindersTransferReminder(
  recordIdentifier: recordIdentifier,
  previousWorkspaceIdentifier: previousWorkspaceIdentifier,
  targetWorkspaceIdentifier: targetWorkspaceIdentifier,
);
