// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<String?> getUserPreference({String? metaWorkspaceId}) => RustLib
    .instance
    .api
    .crateApiUserPreferenceGetUserPreference(metaWorkspaceId: metaWorkspaceId);

Future<String> createUserPreference({
  required String firstName,
  required String lastName,
  required String email,
  String? metaWorkspaceId,
}) => RustLib.instance.api.crateApiUserPreferenceCreateUserPreference(
  firstName: firstName,
  lastName: lastName,
  email: email,
  metaWorkspaceId: metaWorkspaceId,
);

Future<String> updateUserPreference({
  required String identifier,
  String? firstName,
  String? lastName,
  String? email,
  String? metaWorkspaceId,
}) => RustLib.instance.api.crateApiUserPreferenceUpdateUserPreference(
  identifier: identifier,
  firstName: firstName,
  lastName: lastName,
  email: email,
  metaWorkspaceId: metaWorkspaceId,
);

Future<void> duplicateUserPreference({
  required String recordIdentifier,
  required String previousWorkspaceIdentifier,
  required String targetWorkspaceIdentifier,
}) => RustLib.instance.api.crateApiUserPreferenceDuplicateUserPreference(
  recordIdentifier: recordIdentifier,
  previousWorkspaceIdentifier: previousWorkspaceIdentifier,
  targetWorkspaceIdentifier: targetWorkspaceIdentifier,
);

Future<void> transferUserPreference({
  required String recordIdentifier,
  required String previousWorkspaceIdentifier,
  required String targetWorkspaceIdentifier,
}) => RustLib.instance.api.crateApiUserPreferenceTransferUserPreference(
  recordIdentifier: recordIdentifier,
  previousWorkspaceIdentifier: previousWorkspaceIdentifier,
  targetWorkspaceIdentifier: targetWorkspaceIdentifier,
);
