//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub mod bookmark;
pub mod note_categories;
pub mod notes;
pub mod ollama_conversation_history;
pub mod ollama_conversation_prompt;
pub mod ollama_conversation_response;
pub mod prelude;
pub mod snippets;
pub mod sync_queue;
pub mod todo;
