// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Tag } from "./sea_orm_active_enums";

export type Model = {
  identifier: string;
  title: string;
  url: string;
  tag: Tag;
  createdAt: string;
  updatedAt: string;
  workspaceIdentifier: string | null;
};
