// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type Model = {
  identifier: string;
  title: string;
  content: string;
  categories: JsonValue | null;
  createdAt: string;
  updatedAt: string;
  workspaceIdentifier: string | null;
};
