// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItemType } from "./sea_orm_active_enums";

export type Model = {
  identifier: string;
  itemId: string;
  itemType: ItemType;
  payload: string;
  deletedAt: string;
  workspaceIdentifier: string | null;
};
