// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Model = { identifier: string, title: string, description: string | null, recurring: boolean, recurrenceRule: string | null, alarmSound: string | null, remindAt: string, createdAt: string, updatedAt: string, workspaceIdentifier: string | null, };
