// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Model = { identifier: string, title: string | null, language: string | null, code: string, description: string | null, isPinned: boolean, createdAt: string, updatedAt: string, };
