// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Priority } from "./sea_orm_active_enums";

export type Model = {
  identifier: string;
  title: string;
  description: string | null;
  dueDate: string | null;
  priority: Priority;
  done: boolean;
  createdAt: string;
  updatedAt: string;
  dueTime: string | null;
  workspaceIdentifier: string | null;
};
