// Auto-generated by BoltFFI. Do not edit.
// swiftlint:disable all
// swiftformat:disable all

import Foundation
import AlmondKernelFFI
typealias BoltFFICallbackHandle = AlmondKernelFFI.BoltFFICallbackHandle

public struct FfiError: Error {
    public let message: String
    public init(message: String) { self.message = message }
    public init(fromC c: AlmondKernelFFI.FfiError) {
        self.message = stringFromFfi(c.message)
    }
}

public struct CreateBookmark: Hashable, Equatable, Sendable {
    public var title: String
    public var url: String
    public var tag: BookmarkTag

    public init(title: String, url: String, tag: BookmarkTag) {
        self.title = title
        self.url = url
        self.tag = tag
    }

}

extension CreateBookmark: WireCodable {
    @inlinable static func decode(from reader: inout WireReader) -> CreateBookmark {
        CreateBookmark(title: reader.readString(), url: reader.readString(), tag: BookmarkTag(wireTag: reader.readI32()))
    }
    @inlinable func encode(to writer: inout WireWriter) {
        writer.writeString(self.title)
        writer.writeString(self.url)
        writer.writeI32(self.tag.wireTag)
    }
}

public struct UpdateBookmark: Hashable, Equatable, Sendable {
    public var title: String?
    public var url: String?
    public var tag: BookmarkTag?

    public init(title: String? = nil, url: String? = nil, tag: BookmarkTag? = nil) {
        self.title = title
        self.url = url
        self.tag = tag
    }

}

extension UpdateBookmark: WireCodable {
    @inlinable static func decode(from reader: inout WireReader) -> UpdateBookmark {
        UpdateBookmark(title: reader.readOptional { reader in reader.readString() }, url: reader.readOptional { reader in reader.readString() }, tag: reader.readOptional { reader in BookmarkTag(wireTag: reader.readI32()) })
    }
    @inlinable func encode(to writer: inout WireWriter) {
        writer.writeOptional(self.title) { writer, v in writer.writeString(v) }
        writer.writeOptional(self.url) { writer, v in writer.writeString(v) }
        writer.writeOptional(self.tag) { writer, v in writer.writeI32(v.wireTag) }
    }
}

public struct RequestMeta: Hashable, Equatable, Sendable {
    public var workspaceIdentifier: UUID

    public init(workspaceIdentifier: UUID) {
        self.workspaceIdentifier = workspaceIdentifier
    }

}

extension RequestMeta: WireCodable {
    @inlinable static func decode(from reader: inout WireReader) -> RequestMeta {
        RequestMeta(workspaceIdentifier: reader.readUuid())
    }
    @inlinable func encode(to writer: inout WireWriter) {
        writer.writeUuid(self.workspaceIdentifier)
    }
}

public struct CreateNote: Hashable, Equatable, Sendable {
    public var title: String
    public var content: String
    public var categories: [String]?
    public var workspaceIdentifier: UUID?

    public init(title: String, content: String, categories: [String]? = nil, workspaceIdentifier: UUID? = nil) {
        self.title = title
        self.content = content
        self.categories = categories
        self.workspaceIdentifier = workspaceIdentifier
    }

}

extension CreateNote: WireCodable {
    @inlinable static func decode(from reader: inout WireReader) -> CreateNote {
        CreateNote(title: reader.readString(), content: reader.readString(), categories: reader.readOptional { reader in reader.readArray { reader in reader.readString() } }, workspaceIdentifier: reader.readOptional { reader in reader.readUuid() })
    }
    @inlinable func encode(to writer: inout WireWriter) {
        writer.writeString(self.title)
        writer.writeString(self.content)
        writer.writeOptional(self.categories) { writer, v in writer.writeArray(v) { writer, item in writer.writeString(item) } }
        writer.writeOptional(self.workspaceIdentifier) { writer, v in writer.writeUuid(v) }
    }
}

public struct UpdateNote: Hashable, Equatable, Sendable {
    public var title: String?
    public var content: String?
    public var categories: [String]?

    public init(title: String? = nil, content: String? = nil, categories: [String]? = nil) {
        self.title = title
        self.content = content
        self.categories = categories
    }

}

extension UpdateNote: WireCodable {
    @inlinable static func decode(from reader: inout WireReader) -> UpdateNote {
        UpdateNote(title: reader.readOptional { reader in reader.readString() }, content: reader.readOptional { reader in reader.readString() }, categories: reader.readOptional { reader in reader.readArray { reader in reader.readString() } })
    }
    @inlinable func encode(to writer: inout WireWriter) {
        writer.writeOptional(self.title) { writer, v in writer.writeString(v) }
        writer.writeOptional(self.content) { writer, v in writer.writeString(v) }
        writer.writeOptional(self.categories) { writer, v in writer.writeArray(v) { writer, item in writer.writeString(item) } }
    }
}

public struct CreateConversationHistory: Hashable, Equatable, Sendable {
    public var bookmarked: Bool

    public init(bookmarked: Bool) {
        self.bookmarked = bookmarked
    }

}

extension CreateConversationHistory: WireCodable {
    @inlinable static func decode(from reader: inout WireReader) -> CreateConversationHistory { reader.readBlittable() }
    @inlinable func encode(to writer: inout WireWriter) { writer.writeBlittable(self) }
}

public struct UpdateConversationHistory: Hashable, Equatable, Sendable {
    public var bookmarked: Bool?

    public init(bookmarked: Bool? = nil) {
        self.bookmarked = bookmarked
    }

}

extension UpdateConversationHistory: WireCodable {
    @inlinable static func decode(from reader: inout WireReader) -> UpdateConversationHistory {
        UpdateConversationHistory(bookmarked: reader.readOptional { reader in reader.readBool() })
    }
    @inlinable func encode(to writer: inout WireWriter) {
        writer.writeOptional(self.bookmarked) { writer, v in writer.writeBool(v) }
    }
}

public struct CreateConversationPrompt: Hashable, Equatable, Sendable {
    public var historyId: UUID
    public var content: String

    public init(historyId: UUID, content: String) {
        self.historyId = historyId
        self.content = content
    }

}

extension CreateConversationPrompt: WireCodable {
    @inlinable static func decode(from reader: inout WireReader) -> CreateConversationPrompt {
        CreateConversationPrompt(historyId: reader.readUuid(), content: reader.readString())
    }
    @inlinable func encode(to writer: inout WireWriter) {
        writer.writeUuid(self.historyId)
        writer.writeString(self.content)
    }
}

public struct CreateConversationResponse: Hashable, Equatable, Sendable {
    public var historyId: UUID
    public var content: String

    public init(historyId: UUID, content: String) {
        self.historyId = historyId
        self.content = content
    }

}

extension CreateConversationResponse: WireCodable {
    @inlinable static func decode(from reader: inout WireReader) -> CreateConversationResponse {
        CreateConversationResponse(historyId: reader.readUuid(), content: reader.readString())
    }
    @inlinable func encode(to writer: inout WireWriter) {
        writer.writeUuid(self.historyId)
        writer.writeString(self.content)
    }
}

public struct CreateRecycleBinEntry: Hashable, Equatable, Sendable {
    public var itemId: UUID
    public var itemType: RecycleBinItemType
    public var payload: String
    public var workspaceIdentifier: UUID?

    public init(itemId: UUID, itemType: RecycleBinItemType, payload: String, workspaceIdentifier: UUID? = nil) {
        self.itemId = itemId
        self.itemType = itemType
        self.payload = payload
        self.workspaceIdentifier = workspaceIdentifier
    }

}

extension CreateRecycleBinEntry: WireCodable {
    @inlinable static func decode(from reader: inout WireReader) -> CreateRecycleBinEntry {
        CreateRecycleBinEntry(itemId: reader.readUuid(), itemType: RecycleBinItemType(wireTag: reader.readI32()), payload: reader.readString(), workspaceIdentifier: reader.readOptional { reader in reader.readUuid() })
    }
    @inlinable func encode(to writer: inout WireWriter) {
        writer.writeUuid(self.itemId)
        writer.writeI32(self.itemType.wireTag)
        writer.writeString(self.payload)
        writer.writeOptional(self.workspaceIdentifier) { writer, v in writer.writeUuid(v) }
    }
}

public struct CreateReminder: Hashable, Equatable, Sendable {
    public var title: String
    public var description: String?
    public var recurring: Bool
    public var recurrenceRule: String?
    public var alarmSound: String?
    public var workspaceIdentifier: UUID?

    public init(title: String, description: String? = nil, recurring: Bool, recurrenceRule: String? = nil, alarmSound: String? = nil, workspaceIdentifier: UUID? = nil) {
        self.title = title
        self.description = description
        self.recurring = recurring
        self.recurrenceRule = recurrenceRule
        self.alarmSound = alarmSound
        self.workspaceIdentifier = workspaceIdentifier
    }

}

extension CreateReminder: WireCodable {
    @inlinable static func decode(from reader: inout WireReader) -> CreateReminder {
        CreateReminder(title: reader.readString(), description: reader.readOptional { reader in reader.readString() }, recurring: reader.readBool(), recurrenceRule: reader.readOptional { reader in reader.readString() }, alarmSound: reader.readOptional { reader in reader.readString() }, workspaceIdentifier: reader.readOptional { reader in reader.readUuid() })
    }
    @inlinable func encode(to writer: inout WireWriter) {
        writer.writeString(self.title)
        writer.writeOptional(self.description) { writer, v in writer.writeString(v) }
        writer.writeBool(self.recurring)
        writer.writeOptional(self.recurrenceRule) { writer, v in writer.writeString(v) }
        writer.writeOptional(self.alarmSound) { writer, v in writer.writeString(v) }
        writer.writeOptional(self.workspaceIdentifier) { writer, v in writer.writeUuid(v) }
    }
}

public struct UpdateReminder: Hashable, Equatable, Sendable {
    public var title: String?
    public var description: String?
    public var recurring: Bool?
    public var recurrenceRule: String?
    public var alarmSound: String?

    public init(title: String? = nil, description: String? = nil, recurring: Bool? = nil, recurrenceRule: String? = nil, alarmSound: String? = nil) {
        self.title = title
        self.description = description
        self.recurring = recurring
        self.recurrenceRule = recurrenceRule
        self.alarmSound = alarmSound
    }

}

extension UpdateReminder: WireCodable {
    @inlinable static func decode(from reader: inout WireReader) -> UpdateReminder {
        UpdateReminder(title: reader.readOptional { reader in reader.readString() }, description: reader.readOptional { reader in reader.readString() }, recurring: reader.readOptional { reader in reader.readBool() }, recurrenceRule: reader.readOptional { reader in reader.readString() }, alarmSound: reader.readOptional { reader in reader.readString() })
    }
    @inlinable func encode(to writer: inout WireWriter) {
        writer.writeOptional(self.title) { writer, v in writer.writeString(v) }
        writer.writeOptional(self.description) { writer, v in writer.writeString(v) }
        writer.writeOptional(self.recurring) { writer, v in writer.writeBool(v) }
        writer.writeOptional(self.recurrenceRule) { writer, v in writer.writeString(v) }
        writer.writeOptional(self.alarmSound) { writer, v in writer.writeString(v) }
    }
}

public struct Snippet: Hashable, Equatable, Sendable {
    public var title: String?
    public var language: String?
    public var code: String
    public var description: String?
    public var isPinned: Bool

    public init(title: String? = nil, language: String? = nil, code: String, description: String? = nil, isPinned: Bool) {
        self.title = title
        self.language = language
        self.code = code
        self.description = description
        self.isPinned = isPinned
    }

}

extension Snippet: WireCodable {
    @inlinable static func decode(from reader: inout WireReader) -> Snippet {
        Snippet(title: reader.readOptional { reader in reader.readString() }, language: reader.readOptional { reader in reader.readString() }, code: reader.readString(), description: reader.readOptional { reader in reader.readString() }, isPinned: reader.readBool())
    }
    @inlinable func encode(to writer: inout WireWriter) {
        writer.writeOptional(self.title) { writer, v in writer.writeString(v) }
        writer.writeOptional(self.language) { writer, v in writer.writeString(v) }
        writer.writeString(self.code)
        writer.writeOptional(self.description) { writer, v in writer.writeString(v) }
        writer.writeBool(self.isPinned)
    }
}

public struct CreateSnippet: Hashable, Equatable, Sendable {
    public var title: String?
    public var language: String?
    public var code: String
    public var description: String?
    public var isPinned: Bool
    public var workspaceIdentifier: UUID?

    public init(title: String? = nil, language: String? = nil, code: String, description: String? = nil, isPinned: Bool, workspaceIdentifier: UUID? = nil) {
        self.title = title
        self.language = language
        self.code = code
        self.description = description
        self.isPinned = isPinned
        self.workspaceIdentifier = workspaceIdentifier
    }

}

extension CreateSnippet: WireCodable {
    @inlinable static func decode(from reader: inout WireReader) -> CreateSnippet {
        CreateSnippet(title: reader.readOptional { reader in reader.readString() }, language: reader.readOptional { reader in reader.readString() }, code: reader.readString(), description: reader.readOptional { reader in reader.readString() }, isPinned: reader.readBool(), workspaceIdentifier: reader.readOptional { reader in reader.readUuid() })
    }
    @inlinable func encode(to writer: inout WireWriter) {
        writer.writeOptional(self.title) { writer, v in writer.writeString(v) }
        writer.writeOptional(self.language) { writer, v in writer.writeString(v) }
        writer.writeString(self.code)
        writer.writeOptional(self.description) { writer, v in writer.writeString(v) }
        writer.writeBool(self.isPinned)
        writer.writeOptional(self.workspaceIdentifier) { writer, v in writer.writeUuid(v) }
    }
}

public struct UpdateSnippet: Hashable, Equatable, Sendable {
    public var title: String?
    public var language: String?
    public var code: String?
    public var description: String?
    public var isPinned: Bool?

    public init(title: String? = nil, language: String? = nil, code: String? = nil, description: String? = nil, isPinned: Bool? = nil) {
        self.title = title
        self.language = language
        self.code = code
        self.description = description
        self.isPinned = isPinned
    }

}

extension UpdateSnippet: WireCodable {
    @inlinable static func decode(from reader: inout WireReader) -> UpdateSnippet {
        UpdateSnippet(title: reader.readOptional { reader in reader.readString() }, language: reader.readOptional { reader in reader.readString() }, code: reader.readOptional { reader in reader.readString() }, description: reader.readOptional { reader in reader.readString() }, isPinned: reader.readOptional { reader in reader.readBool() })
    }
    @inlinable func encode(to writer: inout WireWriter) {
        writer.writeOptional(self.title) { writer, v in writer.writeString(v) }
        writer.writeOptional(self.language) { writer, v in writer.writeString(v) }
        writer.writeOptional(self.code) { writer, v in writer.writeString(v) }
        writer.writeOptional(self.description) { writer, v in writer.writeString(v) }
        writer.writeOptional(self.isPinned) { writer, v in writer.writeBool(v) }
    }
}

public struct SyncQueueEntry: Hashable, Equatable, Sendable {
    public var tableName: String
    public var recordIdentifier: String
    public var operation: String
    public var createdAt: String

    public init(tableName: String, recordIdentifier: String, operation: String, createdAt: String) {
        self.tableName = tableName
        self.recordIdentifier = recordIdentifier
        self.operation = operation
        self.createdAt = createdAt
    }

}

extension SyncQueueEntry: WireCodable {
    @inlinable static func decode(from reader: inout WireReader) -> SyncQueueEntry {
        SyncQueueEntry(tableName: reader.readString(), recordIdentifier: reader.readString(), operation: reader.readString(), createdAt: reader.readString())
    }
    @inlinable func encode(to writer: inout WireWriter) {
        writer.writeString(self.tableName)
        writer.writeString(self.recordIdentifier)
        writer.writeString(self.operation)
        writer.writeString(self.createdAt)
    }
}

public struct CreateTodo: Hashable, Equatable, Sendable {
    public var title: String
    public var description: String?
    public var priority: TodoPriority

    public init(title: String, description: String? = nil, priority: TodoPriority) {
        self.title = title
        self.description = description
        self.priority = priority
    }

}

extension CreateTodo: WireCodable {
    @inlinable static func decode(from reader: inout WireReader) -> CreateTodo {
        CreateTodo(title: reader.readString(), description: reader.readOptional { reader in reader.readString() }, priority: TodoPriority(wireTag: reader.readI32()))
    }
    @inlinable func encode(to writer: inout WireWriter) {
        writer.writeString(self.title)
        writer.writeOptional(self.description) { writer, v in writer.writeString(v) }
        writer.writeI32(self.priority.wireTag)
    }
}

public struct UpdateTodo: Hashable, Equatable, Sendable {
    public var title: String?
    public var description: String?

    public init(title: String? = nil, description: String? = nil) {
        self.title = title
        self.description = description
    }

}

extension UpdateTodo: WireCodable {
    @inlinable static func decode(from reader: inout WireReader) -> UpdateTodo {
        UpdateTodo(title: reader.readOptional { reader in reader.readString() }, description: reader.readOptional { reader in reader.readString() })
    }
    @inlinable func encode(to writer: inout WireWriter) {
        writer.writeOptional(self.title) { writer, v in writer.writeString(v) }
        writer.writeOptional(self.description) { writer, v in writer.writeString(v) }
    }
}

public struct CreateUserPreference: Hashable, Equatable, Sendable {
    public var firstName: String
    public var lastName: String
    public var email: String

    public init(firstName: String, lastName: String, email: String) {
        self.firstName = firstName
        self.lastName = lastName
        self.email = email
    }

}

extension CreateUserPreference: WireCodable {
    @inlinable static func decode(from reader: inout WireReader) -> CreateUserPreference {
        CreateUserPreference(firstName: reader.readString(), lastName: reader.readString(), email: reader.readString())
    }
    @inlinable func encode(to writer: inout WireWriter) {
        writer.writeString(self.firstName)
        writer.writeString(self.lastName)
        writer.writeString(self.email)
    }
}

public struct UpdateUserPreference: Hashable, Equatable, Sendable {
    public var firstName: String?
    public var lastName: String?
    public var email: String?

    public init(firstName: String? = nil, lastName: String? = nil, email: String? = nil) {
        self.firstName = firstName
        self.lastName = lastName
        self.email = email
    }

}

extension UpdateUserPreference: WireCodable {
    @inlinable static func decode(from reader: inout WireReader) -> UpdateUserPreference {
        UpdateUserPreference(firstName: reader.readOptional { reader in reader.readString() }, lastName: reader.readOptional { reader in reader.readString() }, email: reader.readOptional { reader in reader.readString() })
    }
    @inlinable func encode(to writer: inout WireWriter) {
        writer.writeOptional(self.firstName) { writer, v in writer.writeString(v) }
        writer.writeOptional(self.lastName) { writer, v in writer.writeString(v) }
        writer.writeOptional(self.email) { writer, v in writer.writeString(v) }
    }
}

public struct CreateWorkspace: Hashable, Equatable, Sendable {
    public var name: String
    public var description: String

    public init(name: String, description: String) {
        self.name = name
        self.description = description
    }

}

extension CreateWorkspace: WireCodable {
    @inlinable static func decode(from reader: inout WireReader) -> CreateWorkspace {
        CreateWorkspace(name: reader.readString(), description: reader.readString())
    }
    @inlinable func encode(to writer: inout WireWriter) {
        writer.writeString(self.name)
        writer.writeString(self.description)
    }
}

public struct UpdateWorkspace: Hashable, Equatable, Sendable {
    public var name: String?
    public var description: String?
    public var isDefault: Bool?
    public var isHidden: Bool?
    public var isSecured: Bool?
    /// Plain-text password to be hashed; set to Some("") to remove the password.
    public var password: String?

    public init(name: String? = nil, description: String? = nil, isDefault: Bool? = nil, isHidden: Bool? = nil, isSecured: Bool? = nil, password: String? = nil) {
        self.name = name
        self.description = description
        self.isDefault = isDefault
        self.isHidden = isHidden
        self.isSecured = isSecured
        self.password = password
    }

}

extension UpdateWorkspace: WireCodable {
    @inlinable static func decode(from reader: inout WireReader) -> UpdateWorkspace {
        UpdateWorkspace(name: reader.readOptional { reader in reader.readString() }, description: reader.readOptional { reader in reader.readString() }, isDefault: reader.readOptional { reader in reader.readBool() }, isHidden: reader.readOptional { reader in reader.readBool() }, isSecured: reader.readOptional { reader in reader.readBool() }, password: reader.readOptional { reader in reader.readString() })
    }
    @inlinable func encode(to writer: inout WireWriter) {
        writer.writeOptional(self.name) { writer, v in writer.writeString(v) }
        writer.writeOptional(self.description) { writer, v in writer.writeString(v) }
        writer.writeOptional(self.isDefault) { writer, v in writer.writeBool(v) }
        writer.writeOptional(self.isHidden) { writer, v in writer.writeBool(v) }
        writer.writeOptional(self.isSecured) { writer, v in writer.writeBool(v) }
        writer.writeOptional(self.password) { writer, v in writer.writeString(v) }
    }
}

public struct Model: Hashable, Equatable, Sendable {
    public var name: String
    public var description: String
    public var isDefault: Bool
    public var isHidden: Bool
    public var isSecured: Bool
    public var passwordHash: String?

    public init(name: String, description: String, isDefault: Bool, isHidden: Bool, isSecured: Bool, passwordHash: String? = nil) {
        self.name = name
        self.description = description
        self.isDefault = isDefault
        self.isHidden = isHidden
        self.isSecured = isSecured
        self.passwordHash = passwordHash
    }

}

extension Model: WireCodable {
    @inlinable static func decode(from reader: inout WireReader) -> Model {
        Model(name: reader.readString(), description: reader.readString(), isDefault: reader.readBool(), isHidden: reader.readBool(), isSecured: reader.readBool(), passwordHash: reader.readOptional { reader in reader.readString() })
    }
    @inlinable func encode(to writer: inout WireWriter) {
        writer.writeString(self.name)
        writer.writeString(self.description)
        writer.writeBool(self.isDefault)
        writer.writeBool(self.isHidden)
        writer.writeBool(self.isSecured)
        writer.writeOptional(self.passwordHash) { writer, v in writer.writeString(v) }
    }
}

public enum BookmarkTag: Int32, Hashable, Sendable, CaseIterable {
    case development = 0
    case inspiration = 1
    case design = 2
    case research = 3

    @usableFromInline init(fromC c: Int32) { self = BookmarkTag(rawValue: c)! }
    @usableFromInline var cValue: Int32 { rawValue }
    @usableFromInline init(wireTag: Int32) {
        switch wireTag {
        case 0: self = .development
        case 1: self = .inspiration
        case 2: self = .design
        case 3: self = .research
        default: fatalError("Invalid BookmarkTag wire tag: \\(wireTag)")
        }
    }
    @usableFromInline var wireTag: Int32 {
        switch rawValue {
        case 0: return 0
        case 1: return 1
        case 2: return 2
        case 3: return 3
        default: fatalError("Invalid BookmarkTag raw value: \\(rawValue)")
        }
    }

}

extension BookmarkTag: WireCodable {
    @inlinable static func decode(from reader: inout WireReader) -> BookmarkTag { BookmarkTag(wireTag: reader.readI32()) }
    @inlinable func encode(to writer: inout WireWriter) { writer.writeI32(wireTag) }
}

public enum RecycleBinItemType: Int32, Hashable, Sendable, CaseIterable {
    case todo = 0
    case note = 1
    case reminder = 2
    case snippet = 3
    case bookmark = 4
    case workspace = 5

    @usableFromInline init(fromC c: Int32) { self = RecycleBinItemType(rawValue: c)! }
    @usableFromInline var cValue: Int32 { rawValue }
    @usableFromInline init(wireTag: Int32) {
        switch wireTag {
        case 0: self = .todo
        case 1: self = .note
        case 2: self = .reminder
        case 3: self = .snippet
        case 4: self = .bookmark
        case 5: self = .workspace
        default: fatalError("Invalid RecycleBinItemType wire tag: \\(wireTag)")
        }
    }
    @usableFromInline var wireTag: Int32 {
        switch rawValue {
        case 0: return 0
        case 1: return 1
        case 2: return 2
        case 3: return 3
        case 4: return 4
        case 5: return 5
        default: fatalError("Invalid RecycleBinItemType raw value: \\(rawValue)")
        }
    }

}

extension RecycleBinItemType: WireCodable {
    @inlinable static func decode(from reader: inout WireReader) -> RecycleBinItemType { RecycleBinItemType(wireTag: reader.readI32()) }
    @inlinable func encode(to writer: inout WireWriter) { writer.writeI32(wireTag) }
}

public enum TodoPriority: Int32, Hashable, Sendable, CaseIterable {
    case high = 0
    case medium = 1
    case low = 2

    @usableFromInline init(fromC c: Int32) { self = TodoPriority(rawValue: c)! }
    @usableFromInline var cValue: Int32 { rawValue }
    @usableFromInline init(wireTag: Int32) {
        switch wireTag {
        case 0: self = .high
        case 1: self = .medium
        case 2: self = .low
        default: fatalError("Invalid TodoPriority wire tag: \\(wireTag)")
        }
    }
    @usableFromInline var wireTag: Int32 {
        switch rawValue {
        case 0: return 0
        case 1: return 1
        case 2: return 2
        default: fatalError("Invalid TodoPriority raw value: \\(rawValue)")
        }
    }

}

extension TodoPriority: WireCodable {
    @inlinable static func decode(from reader: inout WireReader) -> TodoPriority { TodoPriority(wireTag: reader.readI32()) }
    @inlinable func encode(to writer: inout WireWriter) { writer.writeI32(wireTag) }
}

@inline(__always)
private func stringFromFfi(_ ffiString: FfiString) -> String {
    guard ffiString.len > 0, let pointer = ffiString.ptr else { return "" }
    return String(decoding: UnsafeBufferPointer(start: pointer, count: Int(ffiString.len)), as: UTF8.self)
}

@inline(__always)
private func takeLastErrorMessage() -> String {
    var out = FfiString()
    ensureOk(boltffi_last_error_message(&out))
    defer { boltffi_free_string(out) }
    return stringFromFfi(out)
}

@inline(__always)
private func checkStatus(_ status: FfiStatus, context: StaticString = #function) throws {
    guard status.code == 0 else {
        throw FfiError(message: "FFI failed in \(context) with code \(status.code)")
    }
}

@inline(__always)
private func ensureOk(_ status: FfiStatus, context: StaticString = #function) {
    guard status.code == 0 else {
        fatalError("FFI failed in \(context) [\(status.code)]")
    }
}

@usableFromInline protocol WireCodable {
    static func decode(from reader: inout WireReader) -> Self
    func encode(to writer: inout WireWriter)
}

@usableFromInline struct WireReader {
    @usableFromInline let data: Data
    @usableFromInline var position: Int
    @inlinable init(ptr: UnsafePointer<UInt8>, len: Int) { self.data = Data(bytes: ptr, count: len); self.position = 0 }

    @inlinable mutating func readU8() -> UInt8 { let v = data[position]; position += 1; return v }
    @inlinable mutating func readI8() -> Int8 { Int8(bitPattern: readU8()) }
    @inlinable mutating func readU16() -> UInt16 { let v = data.withUnsafeBytes { $0.loadUnaligned(fromByteOffset: position, as: UInt16.self) }; position += 2; return v }
    @inlinable mutating func readI16() -> Int16 { Int16(bitPattern: readU16()) }
    @inlinable mutating func readU32() -> UInt32 { let v = data.withUnsafeBytes { $0.loadUnaligned(fromByteOffset: position, as: UInt32.self) }; position += 4; return v }
    @inlinable mutating func readI32() -> Int32 { Int32(bitPattern: readU32()) }
    @inlinable mutating func readU64() -> UInt64 { let v = data.withUnsafeBytes { $0.loadUnaligned(fromByteOffset: position, as: UInt64.self) }; position += 8; return v }
    @inlinable mutating func readI64() -> Int64 { Int64(bitPattern: readU64()) }
    @inlinable mutating func readF32() -> Float { Float(bitPattern: readU32()) }
    @inlinable mutating func readF64() -> Double { Double(bitPattern: readU64()) }
    @inlinable mutating func readBool() -> Bool { readU8() != 0 }

    @inlinable mutating func readString() -> String {
        let len = Int(readU32())
        guard len > 0 else { return "" }
        let start = position
        position += len
        return String(decoding: data[start..<(start + len)], as: UTF8.self)
    }

    @inlinable mutating func readBytes() -> Data {
        let len = Int(readU32())
        guard len > 0 else { return Data() }
        let start = position
        position += len
        return data[start..<(start + len)]
    }

    @inlinable mutating func readDuration() -> TimeInterval {
        let seconds = readU64()
        let nanoseconds = readU32()
        return Double(seconds) + (Double(nanoseconds) / 1.0e9)
    }

    @inlinable mutating func readTimestamp() -> Date {
        let seconds = readI64()
        let nanoseconds = readU32()
        let delta = seconds >= 0
            ? (Double(seconds) + (Double(nanoseconds) / 1.0e9))
            : (Double(seconds) - (Double(nanoseconds) / 1.0e9))
        return Date(timeIntervalSince1970: delta)
    }

    @inlinable mutating func readUuid() -> UUID {
        let hi = readU64()
        let lo = readU64()
        var uuid: uuid_t = (0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
        var hiBe = hi.bigEndian
        var loBe = lo.bigEndian
        withUnsafeMutableBytes(of: &uuid) { uuidBytes in
            Swift.withUnsafeBytes(of: &hiBe) { uuidBytes[0..<8].copyBytes(from: $0) }
            Swift.withUnsafeBytes(of: &loBe) { uuidBytes[8..<16].copyBytes(from: $0) }
        }
        return UUID(uuid: uuid)
    }

    @inlinable mutating func readUrl() -> URL {
        guard let url = URL(string: readString()) else { fatalError("Invalid URL") }
        return url
    }

    @inlinable mutating func readOptional<T>(_ body: (inout WireReader) -> T) -> T? {
        guard readU8() != 0 else { return nil }
        return body(&self)
    }

    @inlinable mutating func readResultOrThrow<T>(
        ok: (inout WireReader) -> T,
        err: (inout WireReader) -> any Error
    ) throws -> T {
        if readU8() == 0 {
            return ok(&self)
        } else {
            throw err(&self)
        }
    }

    @inlinable mutating func readArray<T>(_ body: (inout WireReader) -> T) -> [T] {
        let count = Int(readU32())
        guard count > 0 else { return [] }
        var result = [T]()
        result.reserveCapacity(count)
        for _ in 0..<count { result.append(body(&self)) }
        return result
    }

    @inlinable mutating func readBlittable<T>() -> T {
        let v = data.withUnsafeBytes { $0.loadUnaligned(fromByteOffset: position, as: T.self) }
        position += MemoryLayout<T>.stride
        return v
    }

    @inlinable mutating func readBlittableArray<T>() -> [T] {
        let count = Int(readU32())
        guard count > 0 else { return [] }
        let byteCount = count * MemoryLayout<T>.stride
        let start = position
        position += byteCount
        return data.withUnsafeBytes { rawBuffer in
            Array<T>(unsafeUninitializedCapacity: count) { buffer, initialized in
                memcpy(buffer.baseAddress!, rawBuffer.baseAddress!.advanced(by: start), byteCount)
                initialized = count
            }
        }
    }

    @inlinable mutating func read<T: WireCodable>() -> T {
        T.decode(from: &self)
    }
}

@usableFromInline struct WireWriter {
    @usableFromInline var bytes: [UInt8]
    @inlinable init() { self.bytes = [] }

    @inlinable mutating func writeU8(_ v: UInt8) { bytes.append(v) }
    @inlinable mutating func writeI8(_ v: Int8) { writeU8(UInt8(bitPattern: v)) }
    @inlinable mutating func writeU16(_ v: UInt16) { var val = v; Swift.withUnsafeBytes(of: &val) { bytes.append(contentsOf: $0) } }
    @inlinable mutating func writeI16(_ v: Int16) { writeU16(UInt16(bitPattern: v)) }
    @inlinable mutating func writeU32(_ v: UInt32) { var val = v; Swift.withUnsafeBytes(of: &val) { bytes.append(contentsOf: $0) } }
    @inlinable mutating func writeI32(_ v: Int32) { writeU32(UInt32(bitPattern: v)) }
    @inlinable mutating func writeU64(_ v: UInt64) { var val = v; Swift.withUnsafeBytes(of: &val) { bytes.append(contentsOf: $0) } }
    @inlinable mutating func writeI64(_ v: Int64) { writeU64(UInt64(bitPattern: v)) }
    @inlinable mutating func writeF32(_ v: Float) { writeU32(v.bitPattern) }
    @inlinable mutating func writeF64(_ v: Double) { writeU64(v.bitPattern) }
    @inlinable mutating func writeBool(_ v: Bool) { writeU8(v ? 1 : 0) }

    @inlinable mutating func writeString(_ v: String) {
        var s = v
        s.withUTF8 { utf8 in
            writeU32(UInt32(utf8.count))
            bytes.append(contentsOf: utf8)
        }
    }

    @inlinable mutating func writeBytes(_ v: Data) {
        writeU32(UInt32(v.count))
        bytes.append(contentsOf: v)
    }

    @inlinable mutating func writeDuration(_ v: TimeInterval) {
        if v.rounded(.down) > Double(Int64.max) { fatalError("Duration overflow") }
        if v < 0 { fatalError("Invalid duration") }
        let seconds = UInt64(v)
        let nanoseconds = UInt32((v - Double(seconds)) * 1.0e9)
        writeU64(seconds)
        writeU32(nanoseconds)
    }

    @inlinable mutating func writeTimestamp(_ v: Date) {
        var delta = v.timeIntervalSince1970
        var sign: Int64 = 1
        if delta < 0 { sign = -1; delta = -delta }
        if delta.rounded(.down) > Double(Int64.max) { fatalError("Timestamp overflow") }
        let seconds = Int64(delta)
        let nanoseconds = UInt32((delta - Double(seconds)) * 1.0e9)
        writeI64(sign * seconds)
        writeU32(nanoseconds)
    }

    @inlinable mutating func writeUuid(_ v: UUID) {
        var uuid = v.uuid
        let (hi, lo) = Swift.withUnsafeBytes(of: &uuid) { raw -> (UInt64, UInt64) in
            let hiBe = raw.loadUnaligned(fromByteOffset: 0, as: UInt64.self)
            let loBe = raw.loadUnaligned(fromByteOffset: 8, as: UInt64.self)
            return (UInt64(bigEndian: hiBe), UInt64(bigEndian: loBe))
        }
        writeU64(hi)
        writeU64(lo)
    }

    @inlinable mutating func writeUrl(_ v: URL) { writeString(v.absoluteString) }

    @inlinable mutating func writeOptional<T>(_ v: T?, _ body: (inout WireWriter, T) -> Void) {
        guard let value = v else { writeU8(0); return }
        writeU8(1)
        body(&self, value)
    }

    @inlinable mutating func writeArray<T>(_ v: [T], _ body: (inout WireWriter, T) -> Void) {
        writeU32(UInt32(v.count))
        for item in v { body(&self, item) }
    }

    @inlinable mutating func writeBlittable<T>(_ value: T) {
        var copy = value
        let size = MemoryLayout<T>.size
        let stride = MemoryLayout<T>.stride
        Swift.withUnsafeBytes(of: &copy) { bytes.append(contentsOf: $0) }
        if stride > size {
            bytes.append(contentsOf: repeatElement(UInt8(0), count: stride - size))
        }
    }

    @inlinable mutating func writeBlittableArray<T>(_ v: [T]) {
        writeU32(UInt32(v.count))
        v.withUnsafeBytes { bytes.append(contentsOf: $0) }
    }

    @inlinable mutating func write<T: WireCodable>(_ v: T) { v.encode(to: &self) }

    @inlinable func finalize() -> [UInt8] { bytes }
}

@inlinable func boltffiInvokeWireCallback(
    _ callback: (@convention(c) (UInt64, UnsafePointer<UInt8>?, UInt, FfiStatus) -> Void)?,
    _ callbackData: UInt64,
    _ encoded: [UInt8],
    _ status: FfiStatus
) {
    encoded.withUnsafeBufferPointer { buf in
        callback?(callbackData, buf.baseAddress, UInt(buf.count), status)
    }
}

@inlinable func boltffiDecodeOwnedBuf<T>(_ ptr: UnsafePointer<UInt8>?, _ len: Int, _ decode: (inout WireReader) -> T) -> T {
    var reader = WireReader(ptr: ptr!, len: len)
    return decode(&reader)
}

@inlinable func boltffiDecodeOwnedBuf<T>(_ ptr: UnsafePointer<UInt8>?, _ len: Int, _ decode: (inout WireReader) throws -> T) throws -> T {
    var reader = WireReader(ptr: ptr!, len: len)
    return try decode(&reader)
}

@discardableResult
@inlinable func boltffiStoreEncodedCallbackResult(
    _ encoded: [UInt8],
    _ outPtr: UnsafeMutablePointer<UnsafeMutablePointer<UInt8>?>?,
    _ outLen: UnsafeMutablePointer<UInt>?
) -> Bool {
    if encoded.isEmpty {
        outPtr?.pointee = nil
        outLen?.pointee = 0
        return true
    }
    guard let allocated = malloc(encoded.count)?.assumingMemoryBound(to: UInt8.self) else {
        return false
    }
    _ = encoded.withUnsafeBytes { bytes in
        memcpy(allocated, bytes.baseAddress!, bytes.count)
    }
    outPtr?.pointee = allocated
    outLen?.pointee = UInt(encoded.count)
    return true
}

@inlinable func boltffiEncode(_ body: (inout WireWriter) -> Void) -> [UInt8] {
    var writer = WireWriter()
    body(&writer)
    return writer.finalize()
}
