//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::countries::Entity as Countries;
pub use super::notifications::Entity as Notifications;
pub use super::one_time_passwords::Entity as OneTimePasswords;
pub use super::users::Entity as Users;
